class municipios(object):
    nombres = {
        1: {
            1: 'AGUASCALIENTES',
            2: 'ASIENTOS',
            3: 'CALVILLO',
            4: 'COSÍO',
            5: 'JESÚS MARÍA',
            6: 'PABELLÓN DE ARTEAGA',
            7: 'RINCÓN DE ROMOS',
            8: 'SAN JOSÉ DE GRACIA',
            9: 'TEPEZALÁ',
            10: 'EL LLANO',
            11: 'SAN FRANCISCO DE LOS ROMO',
            999: 'NO ESPECIFICADO',
        }, 2: {
            1: 'ENSENADA',
            2: 'MEXICALI',
            3: 'TECATE',
            4: 'TIJUANA',
            5: 'PLAYAS DE ROSARITO',
            999: 'NO ESPECIFICADO',
        }, 3: {
            1: 'COMONDÚ',
            2: 'MULEGÉ',
            3: 'LA PAZ',
            8: 'LOS CABOS',
            9: 'LORETO',
            999: 'NO ESPECIFICADO',
        }, 4: {
            1: 'CALKINÍ',
            2: 'CAMPECHE',
            3: 'CARMEN',
            4: 'CHAMPOTÓN',
            5: 'HECELCHAKÁN',
            6: 'HOPELCHÉN',
            7: 'PALIZADA',
            8: 'TENABO',
            9: 'ESCÁRCEGA',
            10: 'CALAKMUL',
            11: 'CANDELARIA',
            999: 'NO ESPECIFICADO',
        }, 5: {
            1: 'ABASOLO',
            2: 'ACUÑA',
            3: 'ALLENDE',
            4: 'ARTEAGA',
            5: 'CANDELA',
            6: 'CASTAÑOS',
            7: 'CUATRO CIÉNEGAS',
            8: 'ESCOBEDO',
            9: 'FRANCISCO I. MADERO',
            10: 'FRONTERA',
            11: 'GENERAL CEPEDA',
            12: 'GUERRERO',
            13: 'HIDALGO',
            14: 'JIMÉNEZ',
            15: 'JUÁREZ',
            16: 'LAMADRID',
            17: 'MATAMOROS',
            18: 'MONCLOVA',
            19: 'MORELOS',
            20: 'MÚZQUIZ',
            21: 'NADADORES',
            22: 'NAVA',
            23: 'OCAMPO',
            24: 'PARRAS',
            25: 'PIEDRAS NEGRAS',
            26: 'PROGRESO',
            27: 'RAMOS ARIZPE',
            28: 'SABINAS',
            29: 'SACRAMENTO',
            30: 'SALTILLO',
            31: 'SAN BUENAVENTURA',
            32: 'SAN JUAN DE SABINAS',
            33: 'SAN PEDRO',
            34: 'SIERRA MOJADA',
            35: 'TORREÓN',
            36: 'VIESCA',
            37: 'VILLA UNIÓN',
            38: 'ZARAGOZA',
            999: 'NO ESPECIFICADO',
        }, 6: {
            1: 'ARMERÍA',
            2: 'COLIMA',
            3: 'COMALA',
            4: 'COQUIMATLÁN',
            5: 'CUAUHTÉMOC',
            6: 'IXTLAHUACÁN',
            7: 'MANZANILLO',
            8: 'MINATITLÁN',
            9: 'TECOMÁN',
            10: 'VILLA DE ÁLVAREZ',
            999: 'NO ESPECIFICADO',
        }, 7: {
            1: 'ACACOYAGUA',
            2: 'ACALA',
            3: 'ACAPETAHUA',
            4: 'ALTAMIRANO',
            5: 'AMATÁN',
            6: 'AMATENANGO DE LA FRONTERA',
            7: 'AMATENANGO DEL VALLE',
            8: 'ANGEL ALBINO CORZO',
            9: 'ARRIAGA',
            10: 'BEJUCAL DE OCAMPO',
            11: 'BELLA VISTA',
            12: 'BERRIOZÁBAL',
            13: 'BOCHIL',
            14: 'EL BOSQUE',
            15: 'CACAHOATÁN',
            16: 'CATAZAJÁ',
            17: 'CINTALAPA',
            18: 'COAPILLA',
            19: 'COMITÁN DE DOMÍNGUEZ',
            20: 'LA CONCORDIA',
            21: 'COPAINALÁ',
            22: 'CHALCHIHUITÁN',
            23: 'CHAMULA',
            24: 'CHANAL',
            25: 'CHAPULTENANGO',
            26: 'CHENALHÓ',
            27: 'CHIAPA DE CORZO',
            28: 'CHIAPILLA',
            29: 'CHICOASÉN',
            30: 'CHICOMUSELO',
            31: 'CHILÓN',
            32: 'ESCUINTLA',
            33: 'FRANCISCO LEÓN',
            34: 'FRONTERA COMALAPA',
            35: 'FRONTERA HIDALGO',
            36: 'LA GRANDEZA',
            37: 'HUEHUETÁN',
            38: 'HUIXTÁN',
            39: 'HUITIUPÁN',
            40: 'HUIXTLA',
            41: 'LA INDEPENDENCIA',
            42: 'IXHUATÁN',
            43: 'IXTACOMITÁN',
            44: 'IXTAPA',
            45: 'IXTAPANGAJOYA',
            46: 'JIQUIPILAS',
            47: 'JITOTOL',
            48: 'JUÁREZ',
            49: 'LARRÁINZAR',
            50: 'LA LIBERTAD',
            51: 'MAPASTEPEC',
            52: 'LAS MARGARITAS',
            53: 'MAZAPA DE MADERO',
            54: 'MAZATÁN',
            55: 'METAPA',
            56: 'MITONTIC',
            57: 'MOTOZINTLA',
            58: 'NICOLÁS RUÍZ',
            59: 'OCOSINGO',
            60: 'OCOTEPEC',
            61: 'OCOZOCOAUTLA DE ESPINOSA',
            62: 'OSTUACÁN',
            63: 'OSUMACINTA',
            64: 'OXCHUC',
            65: 'PALENQUE',
            66: 'PANTELHÓ',
            67: 'PANTEPEC',
            68: 'PICHUCALCO',
            69: 'PIJIJIAPAN',
            70: 'EL PORVENIR',
            71: 'VILLA COMALTITLÁN',
            72: 'PUEBLO NUEVO SOLISTAHUACÁN',
            73: 'RAYÓN',
            74: 'REFORMA',
            75: 'LAS ROSAS',
            76: 'SABANILLA',
            77: 'SALTO DE AGUA',
            78: 'SAN CRISTÓBAL DE LAS CASAS',
            79: 'SAN FERNANDO',
            80: 'SILTEPEC',
            81: 'SIMOJOVEL',
            82: 'SITALÁ',
            83: 'SOCOLTENANGO',
            84: 'SOLOSUCHIAPA',
            85: 'SOYALÓ',
            86: 'SUCHIAPA',
            87: 'SUCHIATE',
            88: 'SUNUAPA',
            89: 'TAPACHULA',
            90: 'TAPALAPA',
            91: 'TAPILULA',
            92: 'TECPATÁN',
            93: 'TENEJAPA',
            94: 'TEOPISCA',
            96: 'TILA',
            97: 'TONALÁ',
            98: 'TOTOLAPA',
            99: 'LA TRINITARIA',
            100: 'TUMBALÁ',
            101: 'TUXTLA GUTIÉRREZ',
            102: 'TUXTLA CHICO',
            103: 'TUZANTÁN',
            104: 'TZIMOL',
            105: 'UNIÓN JUÁREZ',
            106: 'VENUSTIANO CARRANZA',
            107: 'VILLA CORZO',
            108: 'VILLAFLORES',
            109: 'YAJALÓN',
            110: 'SAN LUCAS',
            111: 'ZINACANTÁN',
            112: 'SAN JUAN CANCUC',
            113: 'ALDAMA',
            114: 'BENEMÉRITO DE LAS AMÉRICAS',
            115: 'MARAVILLA TENEJAPA',
            116: 'MARQUÉS DE COMILLAS',
            117: 'MONTECRISTO DE GUERRERO',
            118: 'SAN ANDRÉS DURAZNAL',
            119: 'SANTIAGO EL PINAR',
            120: 'CAPITÁN LUIS ÁNGEL VIDAL',
            121: 'RINCÓN CHAMULA SAN PEDRO',
            122: 'EL PARRAL',
            123: 'EMILIANO ZAPATA',
            124: 'MEZCALAPA',
            999: 'NO ESPECIFICADO',
        }, 8: {
            1: 'AHUMADA',
            2: 'ALDAMA',
            3: 'ALLENDE',
            4: 'AQUILES SERDÁN',
            5: 'ASCENSIÓN',
            6: 'BACHÍNIVA',
            7: 'BALLEZA',
            8: 'BATOPILAS DE MANUEL GÓMEZ MORÍN',
            9: 'BOCOYNA',
            10: 'BUENAVENTURA',
            11: 'CAMARGO',
            12: 'CARICHÍ',
            13: 'CASAS GRANDES',
            14: 'CORONADO',
            15: 'COYAME DEL SOTOL',
            16: 'LA CRUZ',
            17: 'CUAUHTÉMOC',
            18: 'CUSIHUIRIACHI',
            19: 'CHIHUAHUA',
            20: 'CHÍNIPAS',
            21: 'DELICIAS',
            22: 'DR. BELISARIO DOMÍNGUEZ',
            23: 'GALEANA',
            24: 'SANTA ISABEL',
            25: 'GÓMEZ FARÍAS',
            26: 'GRAN MORELOS',
            27: 'GUACHOCHI',
            28: 'GUADALUPE',
            29: 'GUADALUPE Y CALVO',
            30: 'GUAZAPARES',
            31: 'GUERRERO',
            32: 'HIDALGO DEL PARRAL',
            33: 'HUEJOTITÁN',
            34: 'IGNACIO ZARAGOZA',
            35: 'JANOS',
            36: 'JIMÉNEZ',
            37: 'JUÁREZ',
            38: 'JULIMES',
            39: 'LÓPEZ',
            40: 'MADERA',
            41: 'MAGUARICHI',
            42: 'MANUEL BENAVIDES',
            43: 'MATACHÍ',
            44: 'MATAMOROS',
            45: 'MEOQUI',
            46: 'MORELOS',
            47: 'MORIS',
            48: 'NAMIQUIPA',
            49: 'NONOAVA',
            50: 'NUEVO CASAS GRANDES',
            51: 'OCAMPO',
            52: 'OJINAGA',
            53: 'PRAXEDIS G. GUERRERO',
            54: 'RIVA PALACIO',
            55: 'ROSALES',
            56: 'ROSARIO',
            57: 'SAN FRANCISCO DE BORJA',
            58: 'SAN FRANCISCO DE CONCHOS',
            59: 'SAN FRANCISCO DEL ORO',
            60: 'SANTA BÁRBARA',
            61: 'SATEVÓ',
            62: 'SAUCILLO',
            63: 'TEMÓSACHIC',
            64: 'EL TULE',
            65: 'URIQUE',
            66: 'URUACHI',
            67: 'VALLE DE ZARAGOZA',
            999: 'NO ESPECIFICADO',
        }, 9: {
            2: 'AZCAPOTZALCO',
            3: 'COYOACÁN',
            4: 'CUAJIMALPA DE MORELOS',
            5: 'GUSTAVO A. MADERO',
            6: 'IZTACALCO',
            7: 'IZTAPALAPA',
            8: 'LA MAGDALENA CONTRERAS',
            9: 'MILPA ALTA',
            10: 'ÁLVARO OBREGÓN',
            11: 'TLÁHUAC',
            12: 'TLALPAN',
            13: 'XOCHIMILCO',
            14: 'BENITO JUÁREZ',
            15: 'CUAUHTÉMOC',
            16: 'MIGUEL HIDALGO',
            17: 'VENUSTIANO CARRANZA',
            999: 'NO ESPECIFICADO',
        }, 10: {
            1: 'CANATLÁN',
            2: 'CANELAS',
            3: 'CONETO DE COMONFORT',
            4: 'CUENCAMÉ',
            5: 'DURANGO',
            6: 'GENERAL SIMÓN BOLÍVAR',
            7: 'GÓMEZ PALACIO',
            8: 'GUADALUPE VICTORIA',
            9: 'GUANACEVÍ',
            10: 'HIDALGO',
            11: 'INDÉ',
            12: 'LERDO',
            13: 'MAPIMÍ',
            14: 'MEZQUITAL',
            15: 'NAZAS',
            16: 'NOMBRE DE DIOS',
            17: 'OCAMPO',
            18: 'EL ORO',
            19: 'OTÁEZ',
            20: 'PÁNUCO DE CORONADO',
            21: 'PEÑÓN BLANCO',
            22: 'POANAS',
            23: 'PUEBLO NUEVO',
            24: 'RODEO',
            25: 'SAN BERNARDO',
            26: 'SAN DIMAS',
            27: 'SAN JUAN DE GUADALUPE',
            28: 'SAN JUAN DEL RÍO',
            29: 'SAN LUIS DEL CORDERO',
            30: 'SAN PEDRO DEL GALLO',
            31: 'SANTA CLARA',
            32: 'SANTIAGO PAPASQUIARO',
            33: 'SÚCHIL',
            34: 'TAMAZULA',
            35: 'TEPEHUANES',
            36: 'TLAHUALILO',
            37: 'TOPIA',
            38: 'VICENTE GUERRERO',
            39: 'NUEVO IDEAL',
            999: 'NO ESPECIFICADO',
        }, 11: {
            1: 'ABASOLO',
            2: 'ACÁMBARO',
            3: 'SAN MIGUEL DE ALLENDE',
            4: 'APASEO EL ALTO',
            5: 'APASEO EL GRANDE',
            6: 'ATARJEA',
            7: 'CELAYA',
            8: 'MANUEL DOBLADO',
            9: 'COMONFORT',
            10: 'CORONEO',
            11: 'CORTAZAR',
            12: 'CUERÁMARO',
            13: 'DOCTOR MORA',
            14: 'DOLORES HIDALGO CUNA DE LA INDEPENDENCIA NACIONAL',
            15: 'GUANAJUATO',
            16: 'HUANÍMARO',
            17: 'IRAPUATO',
            18: 'JARAL DEL PROGRESO',
            19: 'JERÉCUARO',
            20: 'LEÓN',
            21: 'MOROLEÓN',
            22: 'OCAMPO',
            23: 'PÉNJAMO',
            24: 'PUEBLO NUEVO',
            25: 'PURÍSIMA DEL RINCÓN',
            26: 'ROMITA',
            27: 'SALAMANCA',
            28: 'SALVATIERRA',
            29: 'SAN DIEGO DE LA UNIÓN',
            30: 'SAN FELIPE',
            31: 'SAN FRANCISCO DEL RINCÓN',
            32: 'SAN JOSÉ ITURBIDE',
            33: 'SAN LUIS DE LA PAZ',
            34: 'SANTA CATARINA',
            35: 'SANTA CRUZ DE JUVENTINO ROSAS',
            36: 'SANTIAGO MARAVATÍO',
            37: 'SILAO DE LA VICTORIA',
            38: 'TARANDACUAO',
            39: 'TARIMORO',
            40: 'TIERRA BLANCA',
            41: 'URIANGATO',
            42: 'VALLE DE SANTIAGO',
            43: 'VICTORIA',
            44: 'VILLAGRÁN',
            45: 'XICHÚ',
            46: 'YURIRIA',
            999: 'NO ESPECIFICADO',
        }, 12: {
            1: 'ACAPULCO DE JUÁREZ',
            2: 'AHUACUOTZINGO',
            3: 'AJUCHITLÁN DEL PROGRESO',
            4: 'ALCOZAUCA DE GUERRERO',
            5: 'ALPOYECA',
            6: 'APAXTLA',
            7: 'ARCELIA',
            8: 'ATENANGO DEL RÍO',
            9: 'ATLAMAJALCINGO DEL MONTE',
            10: 'ATLIXTAC',
            11: 'ATOYAC DE ÁLVAREZ',
            12: 'AYUTLA DE LOS LIBRES',
            13: 'AZOYÚ',
            14: 'BENITO JUÁREZ',
            15: 'BUENAVISTA DE CUÉLLAR',
            16: 'COAHUAYUTLA DE JOSÉ MARÍA IZAZAGA',
            17: 'COCULA',
            18: 'COPALA',
            19: 'COPALILLO',
            20: 'COPANATOYAC',
            21: 'COYUCA DE BENÍTEZ',
            22: 'COYUCA DE CATALÁN',
            23: 'CUAJINICUILAPA',
            24: 'CUALÁC',
            25: 'CUAUTEPEC',
            26: 'CUETZALA DEL PROGRESO',
            27: 'CUTZAMALA DE PINZÓN',
            28: 'CHILAPA DE ÁLVAREZ',
            29: 'CHILPANCINGO DE LOS BRAVO',
            30: 'FLORENCIO VILLARREAL',
            31: 'GENERAL CANUTO A. NERI',
            32: 'GENERAL HELIODORO CASTILLO',
            33: 'HUAMUXTITLÁN',
            34: 'HUITZUCO DE LOS FIGUEROA',
            35: 'IGUALA DE LA INDEPENDENCIA',
            36: 'IGUALAPA',
            37: 'IXCATEOPAN DE CUAUHTÉMOC',
            38: 'ZIHUATANEJO DE AZUETA',
            39: 'JUAN R. ESCUDERO',
            40: 'LEONARDO BRAVO',
            41: 'MALINALTEPEC',
            42: 'MÁRTIR DE CUILAPAN',
            43: 'METLATÓNOC',
            44: 'MOCHITLÁN',
            45: 'OLINALÁ',
            46: 'OMETEPEC',
            47: 'PEDRO ASCENCIO ALQUISIRAS',
            48: 'PETATLÁN',
            49: 'PILCAYA',
            50: 'PUNGARABATO',
            51: 'QUECHULTENANGO',
            52: 'SAN LUIS ACATLÁN',
            53: 'SAN MARCOS',
            54: 'SAN MIGUEL TOTOLAPAN',
            55: 'TAXCO DE ALARCÓN',
            56: 'TECOANAPA',
            57: 'TÉCPAN DE GALEANA',
            58: 'TELOLOAPAN',
            59: 'TEPECOACUILCO DE TRUJANO',
            60: 'TETIPAC',
            61: 'TIXTLA DE GUERRERO',
            62: 'TLACOACHISTLAHUACA',
            63: 'TLACOAPA',
            64: 'TLALCHAPA',
            65: 'TLALIXTAQUILLA DE MALDONADO',
            66: 'TLAPA DE COMONFORT',
            67: 'TLAPEHUALA',
            68: 'LA UNIÓN DE ISIDORO MONTES DE OCA',
            69: 'XALPATLÁHUAC',
            70: 'XOCHIHUEHUETLÁN',
            71: 'XOCHISTLAHUACA',
            72: 'ZAPOTITLÁN TABLAS',
            73: 'ZIRÁNDARO',
            74: 'ZITLALA',
            75: 'EDUARDO NERI',
            76: 'ACATEPEC',
            77: 'MARQUELIA',
            78: 'COCHOAPA EL GRANDE',
            79: 'JOSÉ JOAQUÍN DE HERRERA',
            80: 'JUCHITÁN',
            81: 'ILIATENCO',
            999: 'NO ESPECIFICADO',
        }, 13: {
            1: 'ACATLÁN',
            2: 'ACAXOCHITLÁN',
            3: 'ACTOPAN',
            4: 'AGUA BLANCA DE ITURBIDE',
            5: 'AJACUBA',
            6: 'ALFAJAYUCAN',
            7: 'ALMOLOYA',
            8: 'APAN',
            9: 'EL ARENAL',
            10: 'ATITALAQUIA',
            11: 'ATLAPEXCO',
            12: 'ATOTONILCO EL GRANDE',
            13: 'ATOTONILCO DE TULA',
            14: 'CALNALI',
            15: 'CARDONAL',
            16: 'CUAUTEPEC DE HINOJOSA',
            17: 'CHAPANTONGO',
            18: 'CHAPULHUACÁN',
            19: 'CHILCUAUTLA',
            20: 'ELOXOCHITLÁN',
            21: 'EMILIANO ZAPATA',
            22: 'EPAZOYUCAN',
            23: 'FRANCISCO I. MADERO',
            24: 'HUASCA DE OCAMPO',
            25: 'HUAUTLA',
            26: 'HUAZALINGO',
            27: 'HUEHUETLA',
            28: 'HUEJUTLA DE REYES',
            29: 'HUICHAPAN',
            30: 'IXMIQUILPAN',
            31: 'JACALA DE LEDEZMA',
            32: 'JALTOCÁN',
            33: 'JUÁREZ HIDALGO',
            34: 'LOLOTLA',
            35: 'METEPEC',
            36: 'SAN AGUSTÍN METZQUITITLÁN',
            37: 'METZTITLÁN',
            38: 'MINERAL DEL CHICO',
            39: 'MINERAL DEL MONTE',
            40: 'LA MISIÓN',
            41: 'MIXQUIAHUALA DE JUÁREZ',
            42: 'MOLANGO DE ESCAMILLA',
            43: 'NICOLÁS FLORES',
            44: 'NOPALA DE VILLAGRÁN',
            45: 'OMITLÁN DE JUÁREZ',
            46: 'SAN FELIPE ORIZATLÁN',
            47: 'PACULA',
            48: 'PACHUCA DE SOTO',
            49: 'PISAFLORES',
            50: 'PROGRESO DE OBREGÓN',
            51: 'MINERAL DE LA REFORMA',
            52: 'SAN AGUSTÍN TLAXIACA',
            53: 'SAN BARTOLO TUTOTEPEC',
            54: 'SAN SALVADOR',
            55: 'SANTIAGO DE ANAYA',
            56: 'SANTIAGO TULANTEPEC DE LUGO GUERRERO',
            57: 'SINGUILUCAN',
            58: 'TASQUILLO',
            59: 'TECOZAUTLA',
            60: 'TENANGO DE DORIA',
            61: 'TEPEAPULCO',
            62: 'TEPEHUACÁN DE GUERRERO',
            63: 'TEPEJI DEL RÍO DE OCAMPO',
            64: 'TEPETITLÁN',
            65: 'TETEPANGO',
            66: 'VILLA DE TEZONTEPEC',
            67: 'TEZONTEPEC DE ALDAMA',
            68: 'TIANGUISTENGO',
            69: 'TIZAYUCA',
            70: 'TLAHUELILPAN',
            71: 'TLAHUILTEPA',
            72: 'TLANALAPA',
            73: 'TLANCHINOL',
            74: 'TLAXCOAPAN',
            75: 'TOLCAYUCA',
            76: 'TULA DE ALLENDE',
            77: 'TULANCINGO DE BRAVO',
            78: 'XOCHIATIPAN',
            79: 'XOCHICOATLÁN',
            80: 'YAHUALICA',
            81: 'ZACUALTIPÁN DE ÁNGELES',
            82: 'ZAPOTLÁN DE JUÁREZ',
            83: 'ZEMPOALA',
            84: 'ZIMAPÁN',
            999: 'NO ESPECIFICADO',
        }, 14: {
            1: 'ACATIC',
            2: 'ACATLÁN DE JUÁREZ',
            3: 'AHUALULCO DE MERCADO',
            4: 'AMACUECA',
            5: 'AMATITÁN',
            6: 'AMECA',
            7: 'SAN JUANITO DE ESCOBEDO',
            8: 'ARANDAS',
            9: 'EL ARENAL',
            10: 'ATEMAJAC DE BRIZUELA',
            11: 'ATENGO',
            12: 'ATENGUILLO',
            13: 'ATOTONILCO EL ALTO',
            14: 'ATOYAC',
            15: 'AUTLÁN DE NAVARRO',
            16: 'AYOTLÁN',
            17: 'AYUTLA',
            18: 'LA BARCA',
            19: 'BOLAÑOS',
            20: 'CABO CORRIENTES',
            21: 'CASIMIRO CASTILLO',
            22: 'CIHUATLÁN',
            23: 'ZAPOTLÁN EL GRANDE',
            24: 'COCULA',
            25: 'COLOTLÁN',
            26: 'CONCEPCIÓN DE BUENOS AIRES',
            27: 'CUAUTITLÁN DE GARCÍA BARRAGÁN',
            28: 'CUAUTLA',
            29: 'CUQUÍO',
            30: 'CHAPALA',
            31: 'CHIMALTITÁN',
            32: 'CHIQUILISTLÁN',
            33: 'DEGOLLADO',
            34: 'EJUTLA',
            35: 'ENCARNACIÓN DE DÍAZ',
            36: 'ETZATLÁN',
            37: 'EL GRULLO',
            38: 'GUACHINANGO',
            39: 'GUADALAJARA',
            40: 'HOSTOTIPAQUILLO',
            41: 'HUEJÚCAR',
            42: 'HUEJUQUILLA EL ALTO',
            43: 'LA HUERTA',
            44: 'IXTLAHUACÁN DE LOS MEMBRILLOS',
            45: 'IXTLAHUACÁN DEL RÍO',
            46: 'JALOSTOTITLÁN',
            47: 'JAMAY',
            48: 'JESÚS MARÍA',
            49: 'JILOTLÁN DE LOS DOLORES',
            50: 'JOCOTEPEC',
            51: 'JUANACATLÁN',
            52: 'JUCHITLÁN',
            53: 'LAGOS DE MORENO',
            54: 'EL LIMÓN',
            55: 'MAGDALENA',
            56: 'SANTA MARÍA DEL ORO',
            57: 'LA MANZANILLA DE LA PAZ',
            58: 'MASCOTA',
            59: 'MAZAMITLA',
            60: 'MEXTICACÁN',
            61: 'MEZQUITIC',
            62: 'MIXTLÁN',
            63: 'OCOTLÁN',
            64: 'OJUELOS DE JALISCO',
            65: 'PIHUAMO',
            66: 'PONCITLÁN',
            67: 'PUERTO VALLARTA',
            68: 'VILLA PURIFICACIÓN',
            69: 'QUITUPAN',
            70: 'EL SALTO',
            71: 'SAN CRISTÓBAL DE LA BARRANCA',
            72: 'SAN DIEGO DE ALEJANDRÍA',
            73: 'SAN JUAN DE LOS LAGOS',
            74: 'SAN JULIÁN',
            75: 'SAN MARCOS',
            76: 'SAN MARTÍN DE BOLAÑOS',
            77: 'SAN MARTÍN HIDALGO',
            78: 'SAN MIGUEL EL ALTO',
            79: 'GÓMEZ FARÍAS',
            80: 'SAN SEBASTIÁN DEL OESTE',
            81: 'SANTA MARÍA DE LOS ÁNGELES',
            82: 'SAYULA',
            83: 'TALA',
            84: 'TALPA DE ALLENDE',
            85: 'TAMAZULA DE GORDIANO',
            86: 'TAPALPA',
            87: 'TECALITLÁN',
            88: 'TECOLOTLÁN',
            89: 'TECHALUTA DE MONTENEGRO',
            90: 'TENAMAXTLÁN',
            91: 'TEOCALTICHE',
            92: 'TEOCUITATLÁN DE CORONA',
            93: 'TEPATITLÁN DE MORELOS',
            94: 'TEQUILA',
            95: 'TEUCHITLÁN',
            96: 'TIZAPÁN EL ALTO',
            97: 'TLAJOMULCO DE ZÚÑIGA',
            98: 'SAN PEDRO TLAQUEPAQUE',
            99: 'TOLIMÁN',
            1: 'TOMATLÁN',
            101: 'TONALÁ',
            102: 'TONAYA',
            103: 'TONILA',
            104: 'TOTATICHE',
            105: 'TOTOTLÁN',
            106: 'TUXCACUESCO',
            107: 'TUXCUECA',
            108: 'TUXPAN',
            109: 'UNIÓN DE SAN ANTONIO',
            110: 'UNIÓN DE TULA',
            111: 'VALLE DE GUADALUPE',
            112: 'VALLE DE JUÁREZ',
            113: 'SAN GABRIEL',
            114: 'VILLA CORONA',
            115: 'VILLA GUERRERO',
            116: 'VILLA HIDALGO',
            117: 'CAÑADAS DE OBREGÓN',
            118: 'YAHUALICA DE GONZÁLEZ GALLO',
            119: 'ZACOALCO DE TORRES',
            120: 'ZAPOPAN',
            121: 'ZAPOTILTIC',
            122: 'ZAPOTITLÁN DE VADILLO',
            123: 'ZAPOTLÁN DEL REY',
            124: 'ZAPOTLANEJO',
            125: 'SAN IGNACIO CERRO GORDO',
            999: 'NO ESPECIFICADO',
        }, 15: {
            1: 'ACAMBAY DE RUÍZ CASTAÑEDA',
            2: 'ACOLMAN',
            3: 'ACULCO',
            4: 'ALMOLOYA DE ALQUISIRAS',
            5: 'ALMOLOYA DE JUÁREZ',
            6: 'ALMOLOYA DEL RÍO',
            7: 'AMANALCO',
            8: 'AMATEPEC',
            9: 'AMECAMECA',
            10: 'APAXCO',
            11: 'ATENCO',
            12: 'ATIZAPÁN',
            13: 'ATIZAPÁN DE ZARAGOZA',
            14: 'ATLACOMULCO',
            15: 'ATLAUTLA',
            16: 'AXAPUSCO',
            17: 'AYAPANGO',
            18: 'CALIMAYA',
            19: 'CAPULHUAC',
            20: 'COACALCO DE BERRIOZÁBAL',
            21: 'COATEPEC HARINAS',
            22: 'COCOTITLÁN',
            23: 'COYOTEPEC',
            24: 'CUAUTITLÁN',
            25: 'CHALCO',
            26: 'CHAPA DE MOTA',
            27: 'CHAPULTEPEC',
            28: 'CHIAUTLA',
            29: 'CHICOLOAPAN',
            30: 'CHICONCUAC',
            31: 'CHIMALHUACÁN',
            32: 'DONATO GUERRA',
            33: 'ECATEPEC DE MORELOS',
            34: 'ECATZINGO',
            35: 'HUEHUETOCA',
            36: 'HUEYPOXTLA',
            37: 'HUIXQUILUCAN',
            38: 'ISIDRO FABELA',
            39: 'IXTAPALUCA',
            40: 'IXTAPAN DE LA SAL',
            41: 'IXTAPAN DEL ORO',
            42: 'IXTLAHUACA',
            43: 'XALATLACO',
            44: 'JALTENCO',
            45: 'JILOTEPEC',
            46: 'JILOTZINGO',
            47: 'JIQUIPILCO',
            48: 'JOCOTITLÁN',
            49: 'JOQUICINGO',
            50: 'JUCHITEPEC',
            51: 'LERMA',
            52: 'MALINALCO',
            53: 'MELCHOR OCAMPO',
            54: 'METEPEC',
            55: 'MEXICALTZINGO',
            56: 'MORELOS',
            57: 'NAUCALPAN DE JUÁREZ',
            58: 'NEZAHUALCÓYOTL',
            59: 'NEXTLALPAN',
            60: 'NICOLÁS ROMERO',
            61: 'NOPALTEPEC',
            62: 'OCOYOACAC',
            63: 'OCUILAN',
            64: 'EL ORO',
            65: 'OTUMBA',
            66: 'OTZOLOAPAN',
            67: 'OTZOLOTEPEC',
            68: 'OZUMBA',
            69: 'PAPALOTLA',
            70: 'LA PAZ',
            71: 'POLOTITLÁN',
            72: 'RAYÓN',
            73: 'SAN ANTONIO LA ISLA',
            74: 'SAN FELIPE DEL PROGRESO',
            75: 'SAN MARTÍN DE LAS PIRÁMIDES',
            76: 'SAN MATEO ATENCO',
            77: 'SAN SIMÓN DE GUERRERO',
            78: 'SANTO TOMÁS',
            79: 'SOYANIQUILPAN DE JUÁREZ',
            80: 'SULTEPEC',
            81: 'TECÁMAC',
            82: 'TEJUPILCO',
            83: 'TEMAMATLA',
            84: 'TEMASCALAPA',
            85: 'TEMASCALCINGO',
            86: 'TEMASCALTEPEC',
            87: 'TEMOAYA',
            88: 'TENANCINGO',
            89: 'TENANGO DEL AIRE',
            90: 'TENANGO DEL VALLE',
            91: 'TEOLOYUCAN',
            92: 'TEOTIHUACÁN',
            93: 'TEPETLAOXTOC',
            94: 'TEPETLIXPA',
            95: 'TEPOTZOTLÁN',
            96: 'TEQUIXQUIAC',
            97: 'TEXCALTITLÁN',
            98: 'TEXCALYACAC',
            99: 'TEXCOCO',
            1: 'TEZOYUCA',
            101: 'TIANGUISTENCO',
            102: 'TIMILPAN',
            103: 'TLALMANALCO',
            104: 'TLALNEPANTLA DE BAZ',
            105: 'TLATLAYA',
            106: 'TOLUCA',
            107: 'TONATICO',
            108: 'TULTEPEC',
            109: 'TULTITLÁN',
            110: 'VALLE DE BRAVO',
            111: 'VILLA DE ALLENDE',
            112: 'VILLA DEL CARBÓN',
            113: 'VILLA GUERRERO',
            114: 'VILLA VICTORIA',
            115: 'XONACATLÁN',
            116: 'ZACAZONAPAN',
            117: 'ZACUALPAN',
            118: 'ZINACANTEPEC',
            119: 'ZUMPAHUACÁN',
            120: 'ZUMPANGO',
            121: 'CUAUTITLÁN IZCALLI',
            122: 'VALLE DE CHALCO SOLIDARIDAD',
            123: 'LUVIANOS',
            124: 'SAN JOSÉ DEL RINCÓN',
            125: 'TONANITLA',
            999: 'NO ESPECIFICADO',
        }, 16: {
            1: 'ACUITZIO',
            2: 'AGUILILLA',
            3: 'ÁLVARO OBREGÓN',
            4: 'ANGAMACUTIRO',
            5: 'ANGANGUEO',
            6: 'APATZINGÁN',
            7: 'APORO',
            8: 'AQUILA',
            9: 'ARIO',
            10: 'ARTEAGA',
            11: 'BRISEÑAS',
            12: 'BUENAVISTA',
            13: 'CARÁCUARO',
            14: 'COAHUAYANA',
            15: 'COALCOMÁN DE VÁZQUEZ PALLARES',
            16: 'COENEO',
            17: 'CONTEPEC',
            18: 'COPÁNDARO',
            19: 'COTIJA',
            20: 'CUITZEO',
            21: 'CHARAPAN',
            22: 'CHARO',
            23: 'CHAVINDA',
            24: 'CHERÁN',
            25: 'CHILCHOTA',
            26: 'CHINICUILA',
            27: 'CHUCÁNDIRO',
            28: 'CHURINTZIO',
            29: 'CHURUMUCO',
            30: 'ECUANDUREO',
            31: 'EPITACIO HUERTA',
            32: 'ERONGARÍCUARO',
            33: 'GABRIEL ZAMORA',
            34: 'HIDALGO',
            35: 'LA HUACANA',
            36: 'HUANDACAREO',
            37: 'HUANIQUEO',
            38: 'HUETAMO',
            39: 'HUIRAMBA',
            40: 'INDAPARAPEO',
            41: 'IRIMBO',
            42: 'IXTLÁN',
            43: 'JACONA',
            44: 'JIMÉNEZ',
            45: 'JIQUILPAN',
            46: 'JUÁREZ',
            47: 'JUNGAPEO',
            48: 'LAGUNILLAS',
            49: 'MADERO',
            50: 'MARAVATÍO',
            51: 'MARCOS CASTELLANOS',
            52: 'LÁZARO CÁRDENAS',
            53: 'MORELIA',
            54: 'MORELOS',
            55: 'MÚGICA',
            56: 'NAHUATZEN',
            57: 'NOCUPÉTARO',
            58: 'NUEVO PARANGARICUTIRO',
            59: 'NUEVO URECHO',
            60: 'NUMARÁN',
            61: 'OCAMPO',
            62: 'PAJACUARÁN',
            63: 'PANINDÍCUARO',
            64: 'PARÁCUARO',
            65: 'PARACHO',
            66: 'PÁTZCUARO',
            67: 'PENJAMILLO',
            68: 'PERIBÁN',
            69: 'LA PIEDAD',
            70: 'PURÉPERO',
            71: 'PURUÁNDIRO',
            72: 'QUERÉNDARO',
            73: 'QUIROGA',
            74: 'COJUMATLÁN DE RÉGULES',
            75: 'LOS REYES',
            76: 'SAHUAYO',
            77: 'SAN LUCAS',
            78: 'SANTA ANA MAYA',
            79: 'SALVADOR ESCALANTE',
            80: 'SENGUIO',
            81: 'SUSUPUATO',
            82: 'TACÁMBARO',
            83: 'TANCÍTARO',
            84: 'TANGAMANDAPIO',
            85: 'TANGANCÍCUARO',
            86: 'TANHUATO',
            87: 'TARETAN',
            88: 'TARÍMBARO',
            89: 'TEPALCATEPEC',
            90: 'TINGAMBATO',
            91: 'TINGÜINDÍN',
            92: 'TIQUICHEO DE NICOLÁS ROMERO',
            93: 'TLALPUJAHUA',
            94: 'TLAZAZALCA',
            95: 'TOCUMBO',
            96: 'TUMBISCATÍO',
            97: 'TURICATO',
            98: 'TUXPAN',
            99: 'TUZANTLA',
            1: 'TZINTZUNTZAN',
            101: 'TZITZIO',
            102: 'URUAPAN',
            103: 'VENUSTIANO CARRANZA',
            104: 'VILLAMAR',
            105: 'VISTA HERMOSA',
            106: 'YURÉCUARO',
            107: 'ZACAPU',
            108: 'ZAMORA',
            109: 'ZINÁPARO',
            110: 'ZINAPÉCUARO',
            111: 'ZIRACUARETIRO',
            112: 'ZITÁCUARO',
            113: 'JOSÉ SIXTO VERDUZCO',
            999: 'NO ESPECIFICADO',
        }, 17: {
            1: 'AMACUZAC',
            2: 'ATLATLAHUCAN',
            3: 'AXOCHIAPAN',
            4: 'AYALA',
            5: 'COATLÁN DEL RÍO',
            6: 'CUAUTLA',
            7: 'CUERNAVACA',
            8: 'EMILIANO ZAPATA',
            9: 'HUITZILAC',
            10: 'JANTETELCO',
            11: 'JIUTEPEC',
            12: 'JOJUTLA',
            13: 'JONACATEPEC DE LEANDRO VALLE',
            14: 'MAZATEPEC',
            15: 'MIACATLÁN',
            16: 'OCUITUCO',
            17: 'PUENTE DE IXTLA',
            18: 'TEMIXCO',
            19: 'TEPALCINGO',
            20: 'TEPOZTLÁN',
            21: 'TETECALA',
            22: 'TETELA DEL VOLCÁN',
            23: 'TLALNEPANTLA',
            24: 'TLALTIZAPÁN DE ZAPATA',
            25: 'TLAQUILTENANGO',
            26: 'TLAYACAPAN',
            27: 'TOTOLAPAN',
            28: 'XOCHITEPEC',
            29: 'YAUTEPEC',
            30: 'YECAPIXTLA',
            31: 'ZACATEPEC',
            32: 'ZACUALPAN DE AMILPAS',
            33: 'TEMOAC',
            34: 'COATETELCO',
            35: 'XOXOCOTLA',
            999: 'NO ESPECIFICADO',
        }, 18: {
            1: 'ACAPONETA',
            2: 'AHUACATLÁN',
            3: 'AMATLÁN DE CAÑAS',
            4: 'COMPOSTELA',
            5: 'HUAJICORI',
            6: 'IXTLÁN DEL RÍO',
            7: 'JALA',
            8: 'XALISCO',
            9: 'DEL NAYAR',
            10: 'ROSAMORADA',
            11: 'RUÍZ',
            12: 'SAN BLAS',
            13: 'SAN PEDRO LAGUNILLAS',
            14: 'SANTA MARÍA DEL ORO',
            15: 'SANTIAGO IXCUINTLA',
            16: 'TECUALA',
            17: 'TEPIC',
            18: 'TUXPAN',
            19: 'LA YESCA',
            20: 'BAHÍA DE BANDERAS',
            999: 'NO ESPECIFICADO',
        }, 19: {
            1: 'ABASOLO',
            2: 'AGUALEGUAS',
            3: 'LOS ALDAMAS',
            4: 'ALLENDE',
            5: 'ANÁHUAC',
            6: 'APODACA',
            7: 'ARAMBERRI',
            8: 'BUSTAMANTE',
            9: 'CADEREYTA JIMÉNEZ',
            10: 'EL CARMEN',
            11: 'CERRALVO',
            12: 'CIÉNEGA DE FLORES',
            13: 'CHINA',
            14: 'DOCTOR ARROYO',
            15: 'DOCTOR COSS',
            16: 'DOCTOR GONZÁLEZ',
            17: 'GALEANA',
            18: 'GARCÍA',
            19: 'SAN PEDRO GARZA GARCÍA',
            20: 'GENERAL BRAVO',
            21: 'GENERAL ESCOBEDO',
            22: 'GENERAL TERÁN',
            23: 'GENERAL TREVIÑO',
            24: 'GENERAL ZARAGOZA',
            25: 'GENERAL ZUAZUA',
            26: 'GUADALUPE',
            27: 'LOS HERRERAS',
            28: 'HIGUERAS',
            29: 'HUALAHUISES',
            30: 'ITURBIDE',
            31: 'JUÁREZ',
            32: 'LAMPAZOS DE NARANJO',
            33: 'LINARES',
            34: 'MARÍN',
            35: 'MELCHOR OCAMPO',
            36: 'MIER Y NORIEGA',
            37: 'MINA',
            38: 'MONTEMORELOS',
            39: 'MONTERREY',
            40: 'PARÁS',
            41: 'PESQUERÍA',
            42: 'LOS RAMONES',
            43: 'RAYONES',
            44: 'SABINAS HIDALGO',
            45: 'SALINAS VICTORIA',
            46: 'SAN NICOLÁS DE LOS GARZA',
            47: 'HIDALGO',
            48: 'SANTA CATARINA',
            49: 'SANTIAGO',
            50: 'VALLECILLO',
            51: 'VILLALDAMA',
            999: 'NO ESPECIFICADO',
        }, 20: {
            1: 'ABEJONES',
            2: 'ACATLÁN DE PÉREZ FIGUEROA',
            3: 'ASUNCIÓN CACALOTEPEC',
            4: 'ASUNCIÓN CUYOTEPEJI',
            5: 'ASUNCIÓN IXTALTEPEC',
            6: 'ASUNCIÓN NOCHIXTLÁN',
            7: 'ASUNCIÓN OCOTLÁN',
            8: 'ASUNCIÓN TLACOLULITA',
            9: 'AYOTZINTEPEC',
            10: 'EL BARRIO DE LA SOLEDAD',
            11: 'CALIHUALÁ',
            12: 'CANDELARIA LOXICHA',
            13: 'CIÉNEGA DE ZIMATLÁN',
            14: 'CIUDAD IXTEPEC',
            15: 'COATECAS ALTAS',
            16: 'COICOYÁN DE LAS FLORES',
            17: 'LA COMPAÑÍA',
            18: 'CONCEPCIÓN BUENAVISTA',
            19: 'CONCEPCIÓN PÁPALO',
            20: 'CONSTANCIA DEL ROSARIO',
            21: 'COSOLAPA',
            22: 'COSOLTEPEC',
            23: 'CUILÁPAM DE GUERRERO',
            24: 'CUYAMECALCO VILLA DE ZARAGOZA',
            25: 'CHAHUITES',
            26: 'CHALCATONGO DE HIDALGO',
            27: 'CHIQUIHUITLÁN DE BENITO JUÁREZ',
            28: 'HEROICA CIUDAD DE EJUTLA DE CRESPO',
            29: 'ELOXOCHITLÁN DE FLORES MAGÓN',
            30: 'EL ESPINAL',
            31: 'TAMAZULÁPAM DEL ESPÍRITU SANTO',
            32: 'FRESNILLO DE TRUJANO',
            33: 'GUADALUPE ETLA',
            34: 'GUADALUPE DE RAMÍREZ',
            35: 'GUELATAO DE JUÁREZ',
            36: 'GUEVEA DE HUMBOLDT',
            37: 'MESONES HIDALGO',
            38: 'VILLA HIDALGO',
            39: 'HEROICA CIUDAD DE HUAJUAPAN DE LEÓN',
            40: 'HUAUTEPEC',
            41: 'HUAUTLA DE JIMÉNEZ',
            42: 'IXTLÁN DE JUÁREZ',
            43: 'JUCHITÁN DE ZARAGOZA',
            44: 'LOMA BONITA',
            45: 'MAGDALENA APASCO',
            46: 'MAGDALENA JALTEPEC',
            47: 'SANTA MAGDALENA JICOTLÁN',
            48: 'MAGDALENA MIXTEPEC',
            49: 'MAGDALENA OCOTLÁN',
            50: 'MAGDALENA PEÑASCO',
            51: 'MAGDALENA TEITIPAC',
            52: 'MAGDALENA TEQUISISTLÁN',
            53: 'MAGDALENA TLACOTEPEC',
            54: 'MAGDALENA ZAHUATLÁN',
            55: 'MARISCALA DE JUÁREZ',
            56: 'MÁRTIRES DE TACUBAYA',
            57: 'MATÍAS ROMERO AVENDAÑO',
            58: 'MAZATLÁN VILLA DE FLORES',
            59: 'MIAHUATLÁN DE PORFIRIO DÍAZ',
            60: 'MIXISTLÁN DE LA REFORMA',
            61: 'MONJAS',
            62: 'NATIVIDAD',
            63: 'NAZARENO ETLA',
            64: 'NEJAPA DE MADERO',
            65: 'IXPANTEPEC NIEVES',
            66: 'SANTIAGO NILTEPEC',
            67: 'OAXACA DE JUÁREZ',
            68: 'OCOTLÁN DE MORELOS',
            69: 'LA PE',
            70: 'PINOTEPA DE DON LUIS',
            71: 'PLUMA HIDALGO',
            72: 'SAN JOSÉ DEL PROGRESO',
            73: 'PUTLA VILLA DE GUERRERO',
            74: 'SANTA CATARINA QUIOQUITANI',
            75: 'REFORMA DE PINEDA',
            76: 'LA REFORMA',
            77: 'REYES ETLA',
            78: 'ROJAS DE CUAUHTÉMOC',
            79: 'SALINA CRUZ',
            80: 'SAN AGUSTÍN AMATENGO',
            81: 'SAN AGUSTÍN ATENANGO',
            82: 'SAN AGUSTÍN CHAYUCO',
            83: 'SAN AGUSTÍN DE LAS JUNTAS',
            84: 'SAN AGUSTÍN ETLA',
            85: 'SAN AGUSTÍN LOXICHA',
            86: 'SAN AGUSTÍN TLACOTEPEC',
            87: 'SAN AGUSTÍN YATARENI',
            88: 'SAN ANDRÉS CABECERA NUEVA',
            89: 'SAN ANDRÉS DINICUITI',
            90: 'SAN ANDRÉS HUAXPALTEPEC',
            91: 'SAN ANDRÉS HUAYÁPAM',
            92: 'SAN ANDRÉS IXTLAHUACA',
            93: 'SAN ANDRÉS LAGUNAS',
            94: 'SAN ANDRÉS NUXIÑO',
            95: 'SAN ANDRÉS PAXTLÁN',
            96: 'SAN ANDRÉS SINAXTLA',
            97: 'SAN ANDRÉS SOLAGA',
            98: 'SAN ANDRÉS TEOTILÁLPAM',
            99: 'SAN ANDRÉS TEPETLAPA',
            1: 'SAN ANDRÉS YAÁ',
            101: 'SAN ANDRÉS ZABACHE',
            102: 'SAN ANDRÉS ZAUTLA',
            103: 'SAN ANTONINO CASTILLO VELASCO',
            104: 'SAN ANTONINO EL ALTO',
            105: 'SAN ANTONINO MONTE VERDE',
            106: 'SAN ANTONIO ACUTLA',
            107: 'SAN ANTONIO DE LA CAL',
            108: 'SAN ANTONIO HUITEPEC',
            109: 'SAN ANTONIO NANAHUATÍPAM',
            110: 'SAN ANTONIO SINICAHUA',
            111: 'SAN ANTONIO TEPETLAPA',
            112: 'SAN BALTAZAR CHICHICÁPAM',
            113: 'SAN BALTAZAR LOXICHA',
            114: 'SAN BALTAZAR YATZACHI EL BAJO',
            115: 'SAN BARTOLO COYOTEPEC',
            116: 'SAN BARTOLOMÉ AYAUTLA',
            117: 'SAN BARTOLOMÉ LOXICHA',
            118: 'SAN BARTOLOMÉ QUIALANA',
            119: 'SAN BARTOLOMÉ YUCUAÑE',
            120: 'SAN BARTOLOMÉ ZOOGOCHO',
            121: 'SAN BARTOLO SOYALTEPEC',
            122: 'SAN BARTOLO YAUTEPEC',
            123: 'SAN BERNARDO MIXTEPEC',
            124: 'SAN BLAS ATEMPA',
            125: 'SAN CARLOS YAUTEPEC',
            126: 'SAN CRISTÓBAL AMATLÁN',
            127: 'SAN CRISTÓBAL AMOLTEPEC',
            128: 'SAN CRISTÓBAL LACHIRIOAG',
            129: 'SAN CRISTÓBAL SUCHIXTLAHUACA',
            130: 'SAN DIONISIO DEL MAR',
            131: 'SAN DIONISIO OCOTEPEC',
            132: 'SAN DIONISIO OCOTLÁN',
            133: 'SAN ESTEBAN ATATLAHUCA',
            134: 'SAN FELIPE JALAPA DE DÍAZ',
            135: 'SAN FELIPE TEJALÁPAM',
            136: 'SAN FELIPE USILA',
            137: 'SAN FRANCISCO CAHUACUÁ',
            138: 'SAN FRANCISCO CAJONOS',
            139: 'SAN FRANCISCO CHAPULAPA',
            140: 'SAN FRANCISCO CHINDÚA',
            141: 'SAN FRANCISCO DEL MAR',
            142: 'SAN FRANCISCO HUEHUETLÁN',
            143: 'SAN FRANCISCO IXHUATÁN',
            144: 'SAN FRANCISCO JALTEPETONGO',
            145: 'SAN FRANCISCO LACHIGOLÓ',
            146: 'SAN FRANCISCO LOGUECHE',
            147: 'SAN FRANCISCO NUXAÑO',
            148: 'SAN FRANCISCO OZOLOTEPEC',
            149: 'SAN FRANCISCO SOLA',
            150: 'SAN FRANCISCO TELIXTLAHUACA',
            151: 'SAN FRANCISCO TEOPAN',
            152: 'SAN FRANCISCO TLAPANCINGO',
            153: 'SAN GABRIEL MIXTEPEC',
            154: 'SAN ILDEFONSO AMATLÁN',
            155: 'SAN ILDEFONSO SOLA',
            156: 'SAN ILDEFONSO VILLA ALTA',
            157: 'SAN JACINTO AMILPAS',
            158: 'SAN JACINTO TLACOTEPEC',
            159: 'SAN JERÓNIMO COATLÁN',
            160: 'SAN JERÓNIMO SILACAYOAPILLA',
            161: 'SAN JERÓNIMO SOSOLA',
            162: 'SAN JERÓNIMO TAVICHE',
            163: 'SAN JERÓNIMO TECÓATL',
            164: 'SAN JORGE NUCHITA',
            165: 'SAN JOSÉ AYUQUILA',
            166: 'SAN JOSÉ CHILTEPEC',
            167: 'SAN JOSÉ DEL PEÑASCO',
            168: 'SAN JOSÉ ESTANCIA GRANDE',
            169: 'SAN JOSÉ INDEPENDENCIA',
            170: 'SAN JOSÉ LACHIGUIRI',
            171: 'SAN JOSÉ TENANGO',
            172: 'SAN JUAN ACHIUTLA',
            173: 'SAN JUAN ATEPEC',
            174: 'ÁNIMAS TRUJANO',
            175: 'SAN JUAN BAUTISTA ATATLAHUCA',
            176: 'SAN JUAN BAUTISTA COIXTLAHUACA',
            177: 'SAN JUAN BAUTISTA CUICATLÁN',
            178: 'SAN JUAN BAUTISTA GUELACHE',
            179: 'SAN JUAN BAUTISTA JAYACATLÁN',
            180: 'SAN JUAN BAUTISTA LO DE SOTO',
            181: 'SAN JUAN BAUTISTA SUCHITEPEC',
            182: 'SAN JUAN BAUTISTA TLACOATZINTEPEC',
            183: 'SAN JUAN BAUTISTA TLACHICHILCO',
            184: 'SAN JUAN BAUTISTA TUXTEPEC',
            185: 'SAN JUAN CACAHUATEPEC',
            186: 'SAN JUAN CIENEGUILLA',
            187: 'SAN JUAN COATZÓSPAM',
            188: 'SAN JUAN COLORADO',
            189: 'SAN JUAN COMALTEPEC',
            190: 'SAN JUAN COTZOCÓN',
            191: 'SAN JUAN CHICOMEZÚCHIL',
            192: 'SAN JUAN CHILATECA',
            193: 'SAN JUAN DEL ESTADO',
            194: 'SAN JUAN DEL RÍO',
            195: 'SAN JUAN DIUXI',
            196: 'SAN JUAN EVANGELISTA ANALCO',
            197: 'SAN JUAN GUELAVÍA',
            198: 'SAN JUAN GUICHICOVI',
            199: 'SAN JUAN IHUALTEPEC',
            2: 'SAN JUAN JUQUILA MIXES',
            201: 'SAN JUAN JUQUILA VIJANOS',
            202: 'SAN JUAN LACHAO',
            203: 'SAN JUAN LACHIGALLA',
            204: 'SAN JUAN LAJARCIA',
            205: 'SAN JUAN LALANA',
            206: 'SAN JUAN DE LOS CUÉS',
            207: 'SAN JUAN MAZATLÁN',
            208: 'SAN JUAN MIXTEPEC',
            209: 'SAN JUAN MIXTEPEC',
            210: 'SAN JUAN ÑUMÍ',
            211: 'SAN JUAN OZOLOTEPEC',
            212: 'SAN JUAN PETLAPA',
            213: 'SAN JUAN QUIAHIJE',
            214: 'SAN JUAN QUIOTEPEC',
            215: 'SAN JUAN SAYULTEPEC',
            216: 'SAN JUAN TABAÁ',
            217: 'SAN JUAN TAMAZOLA',
            218: 'SAN JUAN TEITA',
            219: 'SAN JUAN TEITIPAC',
            220: 'SAN JUAN TEPEUXILA',
            221: 'SAN JUAN TEPOSCOLULA',
            222: 'SAN JUAN YAEÉ',
            223: 'SAN JUAN YATZONA',
            224: 'SAN JUAN YUCUITA',
            225: 'SAN LORENZO',
            226: 'SAN LORENZO ALBARRADAS',
            227: 'SAN LORENZO CACAOTEPEC',
            228: 'SAN LORENZO CUAUNECUILTITLA',
            229: 'SAN LORENZO TEXMELÚCAN',
            230: 'SAN LORENZO VICTORIA',
            231: 'SAN LUCAS CAMOTLÁN',
            232: 'SAN LUCAS OJITLÁN',
            233: 'SAN LUCAS QUIAVINÍ',
            234: 'SAN LUCAS ZOQUIÁPAM',
            235: 'SAN LUIS AMATLÁN',
            236: 'SAN MARCIAL OZOLOTEPEC',
            237: 'SAN MARCOS ARTEAGA',
            238: 'SAN MARTÍN DE LOS CANSECOS',
            239: 'SAN MARTÍN HUAMELÚLPAM',
            240: 'SAN MARTÍN ITUNYOSO',
            241: 'SAN MARTÍN LACHILÁ',
            242: 'SAN MARTÍN PERAS',
            243: 'SAN MARTÍN TILCAJETE',
            244: 'SAN MARTÍN TOXPALAN',
            245: 'SAN MARTÍN ZACATEPEC',
            246: 'SAN MATEO CAJONOS',
            247: 'CAPULÁLPAM DE MÉNDEZ',
            248: 'SAN MATEO DEL MAR',
            249: 'SAN MATEO YOLOXOCHITLÁN',
            250: 'SAN MATEO ETLATONGO',
            251: 'SAN MATEO NEJÁPAM',
            252: 'SAN MATEO PEÑASCO',
            253: 'SAN MATEO PIÑAS',
            254: 'SAN MATEO RÍO HONDO',
            255: 'SAN MATEO SINDIHUI',
            256: 'SAN MATEO TLAPILTEPEC',
            257: 'SAN MELCHOR BETAZA',
            258: 'SAN MIGUEL ACHIUTLA',
            259: 'SAN MIGUEL AHUEHUETITLÁN',
            260: 'SAN MIGUEL ALOÁPAM',
            261: 'SAN MIGUEL AMATITLÁN',
            262: 'SAN MIGUEL AMATLÁN',
            263: 'SAN MIGUEL COATLÁN',
            264: 'SAN MIGUEL CHICAHUA',
            265: 'SAN MIGUEL CHIMALAPA',
            266: 'SAN MIGUEL DEL PUERTO',
            267: 'SAN MIGUEL DEL RÍO',
            268: 'SAN MIGUEL EJUTLA',
            269: 'SAN MIGUEL EL GRANDE',
            270: 'SAN MIGUEL HUAUTLA',
            271: 'SAN MIGUEL MIXTEPEC',
            272: 'SAN MIGUEL PANIXTLAHUACA',
            273: 'SAN MIGUEL PERAS',
            274: 'SAN MIGUEL PIEDRAS',
            275: 'SAN MIGUEL QUETZALTEPEC',
            276: 'SAN MIGUEL SANTA FLOR',
            277: 'VILLA SOLA DE VEGA',
            278: 'SAN MIGUEL SOYALTEPEC',
            279: 'SAN MIGUEL SUCHIXTEPEC',
            280: 'VILLA TALEA DE CASTRO',
            281: 'SAN MIGUEL TECOMATLÁN',
            282: 'SAN MIGUEL TENANGO',
            283: 'SAN MIGUEL TEQUIXTEPEC',
            284: 'SAN MIGUEL TILQUIÁPAM',
            285: 'SAN MIGUEL TLACAMAMA',
            286: 'SAN MIGUEL TLACOTEPEC',
            287: 'SAN MIGUEL TULANCINGO',
            288: 'SAN MIGUEL YOTAO',
            289: 'SAN NICOLÁS',
            290: 'SAN NICOLÁS HIDALGO',
            291: 'SAN PABLO COATLÁN',
            292: 'SAN PABLO CUATRO VENADOS',
            293: 'SAN PABLO ETLA',
            294: 'SAN PABLO HUITZO',
            295: 'SAN PABLO HUIXTEPEC',
            296: 'SAN PABLO MACUILTIANGUIS',
            297: 'SAN PABLO TIJALTEPEC',
            298: 'SAN PABLO VILLA DE MITLA',
            299: 'SAN PABLO YAGANIZA',
            3: 'SAN PEDRO AMUZGOS',
            301: 'SAN PEDRO APÓSTOL',
            302: 'SAN PEDRO ATOYAC',
            303: 'SAN PEDRO CAJONOS',
            304: 'SAN PEDRO COXCALTEPEC CÁNTAROS',
            305: 'SAN PEDRO COMITANCILLO',
            306: 'SAN PEDRO EL ALTO',
            307: 'SAN PEDRO HUAMELULA',
            308: 'SAN PEDRO HUILOTEPEC',
            309: 'SAN PEDRO IXCATLÁN',
            310: 'SAN PEDRO IXTLAHUACA',
            311: 'SAN PEDRO JALTEPETONGO',
            312: 'SAN PEDRO JICAYÁN',
            313: 'SAN PEDRO JOCOTIPAC',
            314: 'SAN PEDRO JUCHATENGO',
            315: 'SAN PEDRO MÁRTIR',
            316: 'SAN PEDRO MÁRTIR QUIECHAPA',
            317: 'SAN PEDRO MÁRTIR YUCUXACO',
            318: 'SAN PEDRO MIXTEPEC',
            319: 'SAN PEDRO MIXTEPEC',
            320: 'SAN PEDRO MOLINOS',
            321: 'SAN PEDRO NOPALA',
            322: 'SAN PEDRO OCOPETATILLO',
            323: 'SAN PEDRO OCOTEPEC',
            324: 'SAN PEDRO POCHUTLA',
            325: 'SAN PEDRO QUIATONI',
            326: 'SAN PEDRO SOCHIÁPAM',
            327: 'SAN PEDRO TAPANATEPEC',
            328: 'SAN PEDRO TAVICHE',
            329: 'SAN PEDRO TEOZACOALCO',
            330: 'SAN PEDRO TEUTILA',
            331: 'SAN PEDRO TIDAÁ',
            332: 'SAN PEDRO TOPILTEPEC',
            333: 'SAN PEDRO TOTOLÁPAM',
            334: 'VILLA DE TUTUTEPEC',
            335: 'SAN PEDRO YANERI',
            336: 'SAN PEDRO YÓLOX',
            337: 'SAN PEDRO Y SAN PABLO AYUTLA',
            338: 'VILLA DE ETLA',
            339: 'SAN PEDRO Y SAN PABLO TEPOSCOLULA',
            340: 'SAN PEDRO Y SAN PABLO TEQUIXTEPEC',
            341: 'SAN PEDRO YUCUNAMA',
            342: 'SAN RAYMUNDO JALPAN',
            343: 'SAN SEBASTIÁN ABASOLO',
            344: 'SAN SEBASTIÁN COATLÁN',
            345: 'SAN SEBASTIÁN IXCAPA',
            346: 'SAN SEBASTIÁN NICANANDUTA',
            347: 'SAN SEBASTIÁN RÍO HONDO',
            348: 'SAN SEBASTIÁN TECOMAXTLAHUACA',
            349: 'SAN SEBASTIÁN TEITIPAC',
            350: 'SAN SEBASTIÁN TUTLA',
            351: 'SAN SIMÓN ALMOLONGAS',
            352: 'SAN SIMÓN ZAHUATLÁN',
            353: 'SANTA ANA',
            354: 'SANTA ANA ATEIXTLAHUACA',
            355: 'SANTA ANA CUAUHTÉMOC',
            356: 'SANTA ANA DEL VALLE',
            357: 'SANTA ANA TAVELA',
            358: 'SANTA ANA TLAPACOYAN',
            359: 'SANTA ANA YARENI',
            360: 'SANTA ANA ZEGACHE',
            361: 'SANTA CATALINA QUIERÍ',
            362: 'SANTA CATARINA CUIXTLA',
            363: 'SANTA CATARINA IXTEPEJI',
            364: 'SANTA CATARINA JUQUILA',
            365: 'SANTA CATARINA LACHATAO',
            366: 'SANTA CATARINA LOXICHA',
            367: 'SANTA CATARINA MECHOACÁN',
            368: 'SANTA CATARINA MINAS',
            369: 'SANTA CATARINA QUIANÉ',
            370: 'SANTA CATARINA TAYATA',
            371: 'SANTA CATARINA TICUÁ',
            372: 'SANTA CATARINA YOSONOTÚ',
            373: 'SANTA CATARINA ZAPOQUILA',
            374: 'SANTA CRUZ ACATEPEC',
            375: 'SANTA CRUZ AMILPAS',
            376: 'SANTA CRUZ DE BRAVO',
            377: 'SANTA CRUZ ITUNDUJIA',
            378: 'SANTA CRUZ MIXTEPEC',
            379: 'SANTA CRUZ NUNDACO',
            380: 'SANTA CRUZ PAPALUTLA',
            381: 'SANTA CRUZ TACACHE DE MINA',
            382: 'SANTA CRUZ TACAHUA',
            383: 'SANTA CRUZ TAYATA',
            384: 'SANTA CRUZ XITLA',
            385: 'SANTA CRUZ XOXOCOTLÁN',
            386: 'SANTA CRUZ ZENZONTEPEC',
            387: 'SANTA GERTRUDIS',
            388: 'SANTA INÉS DEL MONTE',
            389: 'SANTA INÉS YATZECHE',
            390: 'SANTA LUCÍA DEL CAMINO',
            391: 'SANTA LUCÍA MIAHUATLÁN',
            392: 'SANTA LUCÍA MONTEVERDE',
            393: 'SANTA LUCÍA OCOTLÁN',
            394: 'SANTA MARÍA ALOTEPEC',
            395: 'SANTA MARÍA APAZCO',
            396: 'SANTA MARÍA LA ASUNCIÓN',
            397: 'HEROICA CIUDAD DE TLAXIACO',
            398: 'AYOQUEZCO DE ALDAMA',
            399: 'SANTA MARÍA ATZOMPA',
            4: 'SANTA MARÍA CAMOTLÁN',
            401: 'SANTA MARÍA COLOTEPEC',
            402: 'SANTA MARÍA CORTIJO',
            403: 'SANTA MARÍA COYOTEPEC',
            404: 'SANTA MARÍA CHACHOÁPAM',
            405: 'VILLA DE CHILAPA DE DÍAZ',
            406: 'SANTA MARÍA CHILCHOTLA',
            407: 'SANTA MARÍA CHIMALAPA',
            408: 'SANTA MARÍA DEL ROSARIO',
            409: 'SANTA MARÍA DEL TULE',
            410: 'SANTA MARÍA ECATEPEC',
            411: 'SANTA MARÍA GUELACÉ',
            412: 'SANTA MARÍA GUIENAGATI',
            413: 'SANTA MARÍA HUATULCO',
            414: 'SANTA MARÍA HUAZOLOTITLÁN',
            415: 'SANTA MARÍA IPALAPA',
            416: 'SANTA MARÍA IXCATLÁN',
            417: 'SANTA MARÍA JACATEPEC',
            418: 'SANTA MARÍA JALAPA DEL MARQUÉS',
            419: 'SANTA MARÍA JALTIANGUIS',
            420: 'SANTA MARÍA LACHIXÍO',
            421: 'SANTA MARÍA MIXTEQUILLA',
            422: 'SANTA MARÍA NATIVITAS',
            423: 'SANTA MARÍA NDUAYACO',
            424: 'SANTA MARÍA OZOLOTEPEC',
            425: 'SANTA MARÍA PÁPALO',
            426: 'SANTA MARÍA PEÑOLES',
            427: 'SANTA MARÍA PETAPA',
            428: 'SANTA MARÍA QUIEGOLANI',
            429: 'SANTA MARÍA SOLA',
            430: 'SANTA MARÍA TATALTEPEC',
            431: 'SANTA MARÍA TECOMAVACA',
            432: 'SANTA MARÍA TEMAXCALAPA',
            433: 'SANTA MARÍA TEMAXCALTEPEC',
            434: 'SANTA MARÍA TEOPOXCO',
            435: 'SANTA MARÍA TEPANTLALI',
            436: 'SANTA MARÍA TEXCATITLÁN',
            437: 'SANTA MARÍA TLAHUITOLTEPEC',
            438: 'SANTA MARÍA TLALIXTAC',
            439: 'SANTA MARÍA TONAMECA',
            440: 'SANTA MARÍA TOTOLAPILLA',
            441: 'SANTA MARÍA XADANI',
            442: 'SANTA MARÍA YALINA',
            443: 'SANTA MARÍA YAVESÍA',
            444: 'SANTA MARÍA YOLOTEPEC',
            445: 'SANTA MARÍA YOSOYÚA',
            446: 'SANTA MARÍA YUCUHITI',
            447: 'SANTA MARÍA ZACATEPEC',
            448: 'SANTA MARÍA ZANIZA',
            449: 'SANTA MARÍA ZOQUITLÁN',
            450: 'SANTIAGO AMOLTEPEC',
            451: 'SANTIAGO APOALA',
            452: 'SANTIAGO APÓSTOL',
            453: 'SANTIAGO ASTATA',
            454: 'SANTIAGO ATITLÁN',
            455: 'SANTIAGO AYUQUILILLA',
            456: 'SANTIAGO CACALOXTEPEC',
            457: 'SANTIAGO CAMOTLÁN',
            458: 'SANTIAGO COMALTEPEC',
            459: 'VILLA DE SANTIAGO CHAZUMBA',
            460: 'SANTIAGO CHOÁPAM',
            461: 'SANTIAGO DEL RÍO',
            462: 'SANTIAGO HUAJOLOTITLÁN',
            463: 'SANTIAGO HUAUCLILLA',
            464: 'SANTIAGO IHUITLÁN PLUMAS',
            465: 'SANTIAGO IXCUINTEPEC',
            466: 'SANTIAGO IXTAYUTLA',
            467: 'SANTIAGO JAMILTEPEC',
            468: 'SANTIAGO JOCOTEPEC',
            469: 'SANTIAGO JUXTLAHUACA',
            470: 'SANTIAGO LACHIGUIRI',
            471: 'SANTIAGO LALOPA',
            472: 'SANTIAGO LAOLLAGA',
            473: 'SANTIAGO LAXOPA',
            474: 'SANTIAGO LLANO GRANDE',
            475: 'SANTIAGO MATATLÁN',
            476: 'SANTIAGO MILTEPEC',
            477: 'SANTIAGO MINAS',
            478: 'SANTIAGO NACALTEPEC',
            479: 'SANTIAGO NEJAPILLA',
            480: 'SANTIAGO NUNDICHE',
            481: 'SANTIAGO NUYOÓ',
            482: 'SANTIAGO PINOTEPA NACIONAL',
            483: 'SANTIAGO SUCHILQUITONGO',
            484: 'SANTIAGO TAMAZOLA',
            485: 'SANTIAGO TAPEXTLA',
            486: 'VILLA TEJÚPAM DE LA UNIÓN',
            487: 'SANTIAGO TENANGO',
            488: 'SANTIAGO TEPETLAPA',
            489: 'SANTIAGO TETEPEC',
            490: 'SANTIAGO TEXCALCINGO',
            491: 'SANTIAGO TEXTITLÁN',
            492: 'SANTIAGO TILANTONGO',
            493: 'SANTIAGO TILLO',
            494: 'SANTIAGO TLAZOYALTEPEC',
            495: 'SANTIAGO XANICA',
            496: 'SANTIAGO XIACUÍ',
            497: 'SANTIAGO YAITEPEC',
            498: 'SANTIAGO YAVEO',
            499: 'SANTIAGO YOLOMÉCATL',
            5: 'SANTIAGO YOSONDÚA',
            501: 'SANTIAGO YUCUYACHI',
            502: 'SANTIAGO ZACATEPEC',
            503: 'SANTIAGO ZOOCHILA',
            504: 'NUEVO ZOQUIÁPAM',
            505: 'SANTO DOMINGO INGENIO',
            506: 'SANTO DOMINGO ALBARRADAS',
            507: 'SANTO DOMINGO ARMENTA',
            508: 'SANTO DOMINGO CHIHUITÁN',
            509: 'SANTO DOMINGO DE MORELOS',
            510: 'SANTO DOMINGO IXCATLÁN',
            511: 'SANTO DOMINGO NUXAÁ',
            512: 'SANTO DOMINGO OZOLOTEPEC',
            513: 'SANTO DOMINGO PETAPA',
            514: 'SANTO DOMINGO ROAYAGA',
            515: 'SANTO DOMINGO TEHUANTEPEC',
            516: 'SANTO DOMINGO TEOJOMULCO',
            517: 'SANTO DOMINGO TEPUXTEPEC',
            518: 'SANTO DOMINGO TLATAYÁPAM',
            519: 'SANTO DOMINGO TOMALTEPEC',
            520: 'SANTO DOMINGO TONALÁ',
            521: 'SANTO DOMINGO TONALTEPEC',
            522: 'SANTO DOMINGO XAGACÍA',
            523: 'SANTO DOMINGO YANHUITLÁN',
            524: 'SANTO DOMINGO YODOHINO',
            525: 'SANTO DOMINGO ZANATEPEC',
            526: 'SANTOS REYES NOPALA',
            527: 'SANTOS REYES PÁPALO',
            528: 'SANTOS REYES TEPEJILLO',
            529: 'SANTOS REYES YUCUNÁ',
            530: 'SANTO TOMÁS JALIEZA',
            531: 'SANTO TOMÁS MAZALTEPEC',
            532: 'SANTO TOMÁS OCOTEPEC',
            533: 'SANTO TOMÁS TAMAZULAPAN',
            534: 'SAN VICENTE COATLÁN',
            535: 'SAN VICENTE LACHIXÍO',
            536: 'SAN VICENTE NUÑÚ',
            537: 'SILACAYOÁPAM',
            538: 'SITIO DE XITLAPEHUA',
            539: 'SOLEDAD ETLA',
            540: 'VILLA DE TAMAZULÁPAM DEL PROGRESO',
            541: 'TANETZE DE ZARAGOZA',
            542: 'TANICHE',
            543: 'TATALTEPEC DE VALDÉS',
            544: 'TEOCOCUILCO DE MARCOS PÉREZ',
            545: 'TEOTITLÁN DE FLORES MAGÓN',
            546: 'TEOTITLÁN DEL VALLE',
            547: 'TEOTONGO',
            548: 'TEPELMEME VILLA DE MORELOS',
            549: 'HEROICA VILLA TEZOATLÁN DE SEGURA Y LUNA, CUNA DE LA INDEPENDENCIA DE OAXACA',
            550: 'SAN JERÓNIMO TLACOCHAHUAYA',
            551: 'TLACOLULA DE MATAMOROS',
            552: 'TLACOTEPEC PLUMAS',
            553: 'TLALIXTAC DE CABRERA',
            554: 'TOTONTEPEC VILLA DE MORELOS',
            555: 'TRINIDAD ZAACHILA',
            556: 'LA TRINIDAD VISTA HERMOSA',
            557: 'UNIÓN HIDALGO',
            558: 'VALERIO TRUJANO',
            559: 'SAN JUAN BAUTISTA VALLE NACIONAL',
            560: 'VILLA DÍAZ ORDAZ',
            561: 'YAXE',
            562: 'MAGDALENA YODOCONO DE PORFIRIO DÍAZ',
            563: 'YOGANA',
            564: 'YUTANDUCHI DE GUERRERO',
            565: 'VILLA DE ZAACHILA',
            566: 'SAN MATEO YUCUTINDOO',
            567: 'ZAPOTITLÁN LAGUNAS',
            568: 'ZAPOTITLÁN PALMAS',
            569: 'SANTA INÉS DE ZARAGOZA',
            570: 'ZIMATLÁN DE ÁLVAREZ',
            999: 'NO ESPECIFICADO',
        }, 21: {
            1: 'ACAJETE',
            2: 'ACATENO',
            3: 'ACATLÁN',
            4: 'ACATZINGO',
            5: 'ACTEOPAN',
            6: 'AHUACATLÁN',
            7: 'AHUATLÁN',
            8: 'AHUAZOTEPEC',
            9: 'AHUEHUETITLA',
            10: 'AJALPAN',
            11: 'ALBINO ZERTUCHE',
            12: 'ALJOJUCA',
            13: 'ALTEPEXI',
            14: 'AMIXTLÁN',
            15: 'AMOZOC',
            16: 'AQUIXTLA',
            17: 'ATEMPAN',
            18: 'ATEXCAL',
            19: 'ATLIXCO',
            20: 'ATOYATEMPAN',
            21: 'ATZALA',
            22: 'ATZITZIHUACÁN',
            23: 'ATZITZINTLA',
            24: 'AXUTLA',
            25: 'AYOTOXCO DE GUERRERO',
            26: 'CALPAN',
            27: 'CALTEPEC',
            28: 'CAMOCUAUTLA',
            29: 'CAXHUACAN',
            30: 'COATEPEC',
            31: 'COATZINGO',
            32: 'COHETZALA',
            33: 'COHUECAN',
            34: 'CORONANGO',
            35: 'COXCATLÁN',
            36: 'COYOMEAPAN',
            37: 'COYOTEPEC',
            38: 'CUAPIAXTLA DE MADERO',
            39: 'CUAUTEMPAN',
            40: 'CUAUTINCHÁN',
            41: 'CUAUTLANCINGO',
            42: 'CUAYUCA DE ANDRADE',
            43: 'CUETZALAN DEL PROGRESO',
            44: 'CUYOACO',
            45: 'CHALCHICOMULA DE SESMA',
            46: 'CHAPULCO',
            47: 'CHIAUTLA',
            48: 'CHIAUTZINGO',
            49: 'CHICONCUAUTLA',
            50: 'CHICHIQUILA',
            51: 'CHIETLA',
            52: 'CHIGMECATITLÁN',
            53: 'CHIGNAHUAPAN',
            54: 'CHIGNAUTLA',
            55: 'CHILA',
            56: 'CHILA DE LA SAL',
            57: 'HONEY',
            58: 'CHILCHOTLA',
            59: 'CHINANTLA',
            60: 'DOMINGO ARENAS',
            61: 'ELOXOCHITLÁN',
            62: 'EPATLÁN',
            63: 'ESPERANZA',
            64: 'FRANCISCO Z. MENA',
            65: 'GENERAL FELIPE ÁNGELES',
            66: 'GUADALUPE',
            67: 'GUADALUPE VICTORIA',
            68: 'HERMENEGILDO GALEANA',
            69: 'HUAQUECHULA',
            70: 'HUATLATLAUCA',
            71: 'HUAUCHINANGO',
            72: 'HUEHUETLA',
            73: 'HUEHUETLÁN EL CHICO',
            74: 'HUEJOTZINGO',
            75: 'HUEYAPAN',
            76: 'HUEYTAMALCO',
            77: 'HUEYTLALPAN',
            78: 'HUITZILAN DE SERDÁN',
            79: 'HUITZILTEPEC',
            80: 'ATLEQUIZAYAN',
            81: 'IXCAMILPA DE GUERRERO',
            82: 'IXCAQUIXTLA',
            83: 'IXTACAMAXTITLÁN',
            84: 'IXTEPEC',
            85: 'IZÚCAR DE MATAMOROS',
            86: 'JALPAN',
            87: 'JOLALPAN',
            88: 'JONOTLA',
            89: 'JOPALA',
            90: 'JUAN C. BONILLA',
            91: 'JUAN GALINDO',
            92: 'JUAN N. MÉNDEZ',
            93: 'LAFRAGUA',
            94: 'LIBRES',
            95: 'LA MAGDALENA TLATLAUQUITEPEC',
            96: 'MAZAPILTEPEC DE JUÁREZ',
            97: 'MIXTLA',
            98: 'MOLCAXAC',
            99: 'CAÑADA MORELOS',
            1: 'NAUPAN',
            101: 'NAUZONTLA',
            102: 'NEALTICAN',
            103: 'NICOLÁS BRAVO',
            104: 'NOPALUCAN',
            105: 'OCOTEPEC',
            106: 'OCOYUCAN',
            107: 'OLINTLA',
            108: 'ORIENTAL',
            109: 'PAHUATLÁN',
            110: 'PALMAR DE BRAVO',
            111: 'PANTEPEC',
            112: 'PETLALCINGO',
            113: 'PIAXTLA',
            114: 'PUEBLA',
            115: 'QUECHOLAC',
            116: 'QUIMIXTLÁN',
            117: 'RAFAEL LARA GRAJALES',
            118: 'LOS REYES DE JUÁREZ',
            119: 'SAN ANDRÉS CHOLULA',
            120: 'SAN ANTONIO CAÑADA',
            121: 'SAN DIEGO LA MESA TOCHIMILTZINGO',
            122: 'SAN FELIPE TEOTLALCINGO',
            123: 'SAN FELIPE TEPATLÁN',
            124: 'SAN GABRIEL CHILAC',
            125: 'SAN GREGORIO ATZOMPA',
            126: 'SAN JERÓNIMO TECUANIPAN',
            127: 'SAN JERÓNIMO XAYACATLÁN',
            128: 'SAN JOSÉ CHIAPA',
            129: 'SAN JOSÉ MIAHUATLÁN',
            130: 'SAN JUAN ATENCO',
            131: 'SAN JUAN ATZOMPA',
            132: 'SAN MARTÍN TEXMELUCAN',
            133: 'SAN MARTÍN TOTOLTEPEC',
            134: 'SAN MATÍAS TLALANCALECA',
            135: 'SAN MIGUEL IXITLÁN',
            136: 'SAN MIGUEL XOXTLA',
            137: 'SAN NICOLÁS BUENOS AIRES',
            138: 'SAN NICOLÁS DE LOS RANCHOS',
            139: 'SAN PABLO ANICANO',
            140: 'SAN PEDRO CHOLULA',
            141: 'SAN PEDRO YELOIXTLAHUACA',
            142: 'SAN SALVADOR EL SECO',
            143: 'SAN SALVADOR EL VERDE',
            144: 'SAN SALVADOR HUIXCOLOTLA',
            145: 'SAN SEBASTIÁN TLACOTEPEC',
            146: 'SANTA CATARINA TLALTEMPAN',
            147: 'SANTA INÉS AHUATEMPAN',
            148: 'SANTA ISABEL CHOLULA',
            149: 'SANTIAGO MIAHUATLÁN',
            150: 'HUEHUETLÁN EL GRANDE',
            151: 'SANTO TOMÁS HUEYOTLIPAN',
            152: 'SOLTEPEC',
            153: 'TECALI DE HERRERA',
            154: 'TECAMACHALCO',
            155: 'TECOMATLÁN',
            156: 'TEHUACÁN',
            157: 'TEHUITZINGO',
            158: 'TENAMPULCO',
            159: 'TEOPANTLÁN',
            160: 'TEOTLALCO',
            161: 'TEPANCO DE LÓPEZ',
            162: 'TEPANGO DE RODRÍGUEZ',
            163: 'TEPATLAXCO DE HIDALGO',
            164: 'TEPEACA',
            165: 'TEPEMAXALCO',
            166: 'TEPEOJUMA',
            167: 'TEPETZINTLA',
            168: 'TEPEXCO',
            169: 'TEPEXI DE RODRÍGUEZ',
            170: 'TEPEYAHUALCO',
            171: 'TEPEYAHUALCO DE CUAUHTÉMOC',
            172: 'TETELA DE OCAMPO',
            173: 'TETELES DE AVILA CASTILLO',
            174: 'TEZIUTLÁN',
            175: 'TIANGUISMANALCO',
            176: 'TILAPA',
            177: 'TLACOTEPEC DE BENITO JUÁREZ',
            178: 'TLACUILOTEPEC',
            179: 'TLACHICHUCA',
            180: 'TLAHUAPAN',
            181: 'TLALTENANGO',
            182: 'TLANEPANTLA',
            183: 'TLAOLA',
            184: 'TLAPACOYA',
            185: 'TLAPANALÁ',
            186: 'TLATLAUQUITEPEC',
            187: 'TLAXCO',
            188: 'TOCHIMILCO',
            189: 'TOCHTEPEC',
            190: 'TOTOLTEPEC DE GUERRERO',
            191: 'TULCINGO',
            192: 'TUZAMAPAN DE GALEANA',
            193: 'TZICATLACOYAN',
            194: 'VENUSTIANO CARRANZA',
            195: 'VICENTE GUERRERO',
            196: 'XAYACATLÁN DE BRAVO',
            197: 'XICOTEPEC',
            198: 'XICOTLÁN',
            199: 'XIUTETELCO',
            2: 'XOCHIAPULCO',
            201: 'XOCHILTEPEC',
            202: 'XOCHITLÁN DE VICENTE SUÁREZ',
            203: 'XOCHITLÁN TODOS SANTOS',
            204: 'YAONÁHUAC',
            205: 'YEHUALTEPEC',
            206: 'ZACAPALA',
            207: 'ZACAPOAXTLA',
            208: 'ZACATLÁN',
            209: 'ZAPOTITLÁN',
            210: 'ZAPOTITLÁN DE MÉNDEZ',
            211: 'ZARAGOZA',
            212: 'ZAUTLA',
            213: 'ZIHUATEUTLA',
            214: 'ZINACATEPEC',
            215: 'ZONGOZOTLA',
            216: 'ZOQUIAPAN',
            217: 'ZOQUITLÁN',
            999: 'NO ESPECIFICADO',
        }, 22: {
            1: 'AMEALCO DE BONFIL',
            2: 'PINAL DE AMOLES',
            3: 'ARROYO SECO',
            4: 'CADEREYTA DE MONTES',
            5: 'COLÓN',
            6: 'CORREGIDORA',
            7: 'EZEQUIEL MONTES',
            8: 'HUIMILPAN',
            9: 'JALPAN DE SERRA',
            10: 'LANDA DE MATAMOROS',
            11: 'EL MARQUÉS',
            12: 'PEDRO ESCOBEDO',
            13: 'PEÑAMILLER',
            14: 'QUERÉTARO',
            15: 'SAN JOAQUÍN',
            16: 'SAN JUAN DEL RÍO',
            17: 'TEQUISQUIAPAN',
            18: 'TOLIMÁN',
            999: 'NO ESPECIFICADO',
        }, 23: {
            1: 'COZUMEL',
            2: 'FELIPE CARRILLO PUERTO',
            3: 'ISLA MUJERES',
            4: 'OTHÓN P. BLANCO',
            5: 'BENITO JUÁREZ',
            6: 'JOSÉ MARÍA MORELOS',
            7: 'LÁZARO CÁRDENAS',
            8: 'SOLIDARIDAD',
            9: 'TULUM',
            10: 'BACALAR',
            11: 'PUERTO MORELOS',
            999: 'NO ESPECIFICADO',
        }, 24: {
            1: 'AHUALULCO',
            2: 'ALAQUINES',
            3: 'AQUISMÓN',
            4: 'ARMADILLO DE LOS INFANTE',
            5: 'CÁRDENAS',
            6: 'CATORCE',
            7: 'CEDRAL',
            8: 'CERRITOS',
            9: 'CERRO DE SAN PEDRO',
            10: 'CIUDAD DEL MAÍZ',
            11: 'CIUDAD FERNÁNDEZ',
            12: 'TANCANHUITZ',
            13: 'CIUDAD VALLES',
            14: 'COXCATLÁN',
            15: 'CHARCAS',
            16: 'EBANO',
            17: 'GUADALCÁZAR',
            18: 'HUEHUETLÁN',
            19: 'LAGUNILLAS',
            20: 'MATEHUALA',
            21: 'MEXQUITIC DE CARMONA',
            22: 'MOCTEZUMA',
            23: 'RAYÓN',
            24: 'RIOVERDE',
            25: 'SALINAS',
            26: 'SAN ANTONIO',
            27: 'SAN CIRO DE ACOSTA',
            28: 'SAN LUIS POTOSÍ',
            29: 'SAN MARTÍN CHALCHICUAUTLA',
            30: 'SAN NICOLÁS TOLENTINO',
            31: 'SANTA CATARINA',
            32: 'SANTA MARÍA DEL RÍO',
            33: 'SANTO DOMINGO',
            34: 'SAN VICENTE TANCUAYALAB',
            35: 'SOLEDAD DE GRACIANO SÁNCHEZ',
            36: 'TAMASOPO',
            37: 'TAMAZUNCHALE',
            38: 'TAMPACÁN',
            39: 'TAMPAMOLÓN CORONA',
            40: 'TAMUÍN',
            41: 'TANLAJÁS',
            42: 'TANQUIÁN DE ESCOBEDO',
            43: 'TIERRA NUEVA',
            44: 'VANEGAS',
            45: 'VENADO',
            46: 'VILLA DE ARRIAGA',
            47: 'VILLA DE GUADALUPE',
            48: 'VILLA DE LA PAZ',
            49: 'VILLA DE RAMOS',
            50: 'VILLA DE REYES',
            51: 'VILLA HIDALGO',
            52: 'VILLA JUÁREZ',
            53: 'AXTLA DE TERRAZAS',
            54: 'XILITLA',
            55: 'ZARAGOZA',
            56: 'VILLA DE ARISTA',
            57: 'MATLAPA',
            58: 'EL NARANJO',
            999: 'NO ESPECIFICADO',
        }, 25: {
            1: 'AHOME',
            2: 'ANGOSTURA',
            3: 'BADIRAGUATO',
            4: 'CONCORDIA',
            5: 'COSALÁ',
            6: 'CULIACÁN',
            7: 'CHOIX',
            8: 'ELOTA',
            9: 'ESCUINAPA',
            10: 'EL FUERTE',
            11: 'GUASAVE',
            12: 'MAZATLÁN',
            13: 'MOCORITO',
            14: 'ROSARIO',
            15: 'SALVADOR ALVARADO',
            16: 'SAN IGNACIO',
            17: 'SINALOA',
            18: 'NAVOLATO',
            999: 'NO ESPECIFICADO',
        }, 26: {
            1: 'ACONCHI',
            2: 'AGUA PRIETA',
            3: 'ALAMOS',
            4: 'ALTAR',
            5: 'ARIVECHI',
            6: 'ARIZPE',
            7: 'ATIL',
            8: 'BACADÉHUACHI',
            9: 'BACANORA',
            10: 'BACERAC',
            11: 'BACOACHI',
            12: 'BÁCUM',
            13: 'BANÁMICHI',
            14: 'BAVIÁCORA',
            15: 'BAVISPE',
            16: 'BENJAMÍN HILL',
            17: 'CABORCA',
            18: 'CAJEME',
            19: 'CANANEA',
            20: 'CARBÓ',
            21: 'LA COLORADA',
            22: 'CUCURPE',
            23: 'CUMPAS',
            24: 'DIVISADEROS',
            25: 'EMPALME',
            26: 'ETCHOJOA',
            27: 'FRONTERAS',
            28: 'GRANADOS',
            29: 'GUAYMAS',
            30: 'HERMOSILLO',
            31: 'HUACHINERA',
            32: 'HUÁSABAS',
            33: 'HUATABAMPO',
            34: 'HUÉPAC',
            35: 'IMURIS',
            36: 'MAGDALENA',
            37: 'MAZATÁN',
            38: 'MOCTEZUMA',
            39: 'NACO',
            40: 'NÁCORI CHICO',
            41: 'NACOZARI DE GARCÍA',
            42: 'NAVOJOA',
            43: 'NOGALES',
            44: 'ONAVAS',
            45: 'OPODEPE',
            46: 'OQUITOA',
            47: 'PITIQUITO',
            48: 'PUERTO PEÑASCO',
            49: 'QUIRIEGO',
            50: 'RAYÓN',
            51: 'ROSARIO',
            52: 'SAHUARIPA',
            53: 'SAN FELIPE DE JESÚS',
            54: 'SAN JAVIER',
            55: 'SAN LUIS RÍO COLORADO',
            56: 'SAN MIGUEL DE HORCASITAS',
            57: 'SAN PEDRO DE LA CUEVA',
            58: 'SANTA ANA',
            59: 'SANTA CRUZ',
            60: 'SÁRIC',
            61: 'SOYOPA',
            62: 'SUAQUI GRANDE',
            63: 'TEPACHE',
            64: 'TRINCHERAS',
            65: 'TUBUTAMA',
            66: 'URES',
            67: 'VILLA HIDALGO',
            68: 'VILLA PESQUEIRA',
            69: 'YÉCORA',
            70: 'GENERAL PLUTARCO ELÍAS CALLES',
            71: 'BENITO JUÁREZ',
            72: 'SAN IGNACIO RÍO MUERTO',
            999: 'NO ESPECIFICADO',
        }, 27: {
            1: 'BALANCÁN',
            2: 'CÁRDENAS',
            3: 'CENTLA',
            4: 'CENTRO',
            5: 'COMALCALCO',
            6: 'CUNDUACÁN',
            7: 'EMILIANO ZAPATA',
            8: 'HUIMANGUILLO',
            9: 'JALAPA',
            10: 'JALPA DE MÉNDEZ',
            11: 'JONUTA',
            12: 'MACUSPANA',
            13: 'NACAJUCA',
            14: 'PARAÍSO',
            15: 'TACOTALPA',
            16: 'TEAPA',
            17: 'TENOSIQUE',
            999: 'NO ESPECIFICADO',
        }, 28: {
            1: 'ABASOLO',
            2: 'ALDAMA',
            3: 'ALTAMIRA',
            4: 'ANTIGUO MORELOS',
            5: 'BURGOS',
            6: 'BUSTAMANTE',
            7: 'CAMARGO',
            8: 'CASAS',
            9: 'CIUDAD MADERO',
            10: 'CRUILLAS',
            11: 'GÓMEZ FARÍAS',
            12: 'GONZÁLEZ',
            13: 'GÜÉMEZ',
            14: 'GUERRERO',
            15: 'GUSTAVO DÍAZ ORDAZ',
            16: 'HIDALGO',
            17: 'JAUMAVE',
            18: 'JIMÉNEZ',
            19: 'LLERA',
            20: 'MAINERO',
            21: 'EL MANTE',
            22: 'MATAMOROS',
            23: 'MÉNDEZ',
            24: 'MIER',
            25: 'MIGUEL ALEMÁN',
            26: 'MIQUIHUANA',
            27: 'NUEVO LAREDO',
            28: 'NUEVO MORELOS',
            29: 'OCAMPO',
            30: 'PADILLA',
            31: 'PALMILLAS',
            32: 'REYNOSA',
            33: 'RÍO BRAVO',
            34: 'SAN CARLOS',
            35: 'SAN FERNANDO',
            36: 'SAN NICOLÁS',
            37: 'SOTO LA MARINA',
            38: 'TAMPICO',
            39: 'TULA',
            40: 'VALLE HERMOSO',
            41: 'VICTORIA',
            42: 'VILLAGRÁN',
            43: 'XICOTÉNCATL',
            999: 'NO ESPECIFICADO',
        }, 29: {
            1: 'AMAXAC DE GUERRERO',
            2: 'APETATITLÁN DE ANTONIO CARVAJAL',
            3: 'ATLANGATEPEC',
            4: 'ATLTZAYANCA',
            5: 'APIZACO',
            6: 'CALPULALPAN',
            7: 'EL CARMEN TEQUEXQUITLA',
            8: 'CUAPIAXTLA',
            9: 'CUAXOMULCO',
            10: 'CHIAUTEMPAN',
            11: 'MUÑOZ DE DOMINGO ARENAS',
            12: 'ESPAÑITA',
            13: 'HUAMANTLA',
            14: 'HUEYOTLIPAN',
            15: 'IXTACUIXTLA DE MARIANO MATAMOROS',
            16: 'IXTENCO',
            17: 'MAZATECOCHCO DE JOSÉ MARÍA MORELOS',
            18: 'CONTLA DE JUAN CUAMATZI',
            19: 'TEPETITLA DE LARDIZÁBAL',
            20: 'SANCTÓRUM DE LÁZARO CÁRDENAS',
            21: 'NANACAMILPA DE MARIANO ARISTA',
            22: 'ACUAMANALA DE MIGUEL HIDALGO',
            23: 'NATÍVITAS',
            24: 'PANOTLA',
            25: 'SAN PABLO DEL MONTE',
            26: 'SANTA CRUZ TLAXCALA',
            27: 'TENANCINGO',
            28: 'TEOLOCHOLCO',
            29: 'TEPEYANCO',
            30: 'TERRENATE',
            31: 'TETLA DE LA SOLIDARIDAD',
            32: 'TETLATLAHUCA',
            33: 'TLAXCALA',
            34: 'TLAXCO',
            35: 'TOCATLÁN',
            36: 'TOTOLAC',
            37: 'ZILTLALTÉPEC DE TRINIDAD SÁNCHEZ SANTOS',
            38: 'TZOMPANTEPEC',
            39: 'XALOZTOC',
            40: 'XALTOCAN',
            41: 'PAPALOTLA DE XICOHTÉNCATL',
            42: 'XICOHTZINCO',
            43: 'YAUHQUEMEHCAN',
            44: 'ZACATELCO',
            45: 'BENITO JUÁREZ',
            46: 'EMILIANO ZAPATA',
            47: 'LÁZARO CÁRDENAS',
            48: 'LA MAGDALENA TLALTELULCO',
            49: 'SAN DAMIÁN TEXÓLOC',
            50: 'SAN FRANCISCO TETLANOHCAN',
            51: 'SAN JERÓNIMO ZACUALPAN',
            52: 'SAN JOSÉ TEACALCO',
            53: 'SAN JUAN HUACTZINCO',
            54: 'SAN LORENZO AXOCOMANITLA',
            55: 'SAN LUCAS TECOPILCO',
            56: 'SANTA ANA NOPALUCAN',
            57: 'SANTA APOLONIA TEACALCO',
            58: 'SANTA CATARINA AYOMETLA',
            59: 'SANTA CRUZ QUILEHTLA',
            60: 'SANTA ISABEL XILOXOXTLA',
            999: 'NO ESPECIFICADO',
        }, 30: {
            1: 'ACAJETE',
            2: 'ACATLÁN',
            3: 'ACAYUCAN',
            4: 'ACTOPAN',
            5: 'ACULA',
            6: 'ACULTZINGO',
            7: 'CAMARÓN DE TEJEDA',
            8: 'ALPATLÁHUAC',
            9: 'ALTO LUCERO DE GUTIÉRREZ BARRIOS',
            10: 'ALTOTONGA',
            11: 'ALVARADO',
            12: 'AMATITLÁN',
            13: 'NARANJOS AMATLÁN',
            14: 'AMATLÁN DE LOS REYES',
            15: 'ANGEL R. CABADA',
            16: 'LA ANTIGUA',
            17: 'APAZAPAN',
            18: 'AQUILA',
            19: 'ASTACINGA',
            20: 'ATLAHUILCO',
            21: 'ATOYAC',
            22: 'ATZACAN',
            23: 'ATZALAN',
            24: 'TLALTETELA',
            25: 'AYAHUALULCO',
            26: 'BANDERILLA',
            27: 'BENITO JUÁREZ',
            28: 'BOCA DEL RÍO',
            29: 'CALCAHUALCO',
            30: 'CAMERINO Z. MENDOZA',
            31: 'CARRILLO PUERTO',
            32: 'CATEMACO',
            33: 'CAZONES DE HERRERA',
            34: 'CERRO AZUL',
            35: 'CITLALTÉPETL',
            36: 'COACOATZINTLA',
            37: 'COAHUITLÁN',
            38: 'COATEPEC',
            39: 'COATZACOALCOS',
            40: 'COATZINTLA',
            41: 'COETZALA',
            42: 'COLIPA',
            43: 'COMAPA',
            44: 'CÓRDOBA',
            45: 'COSAMALOAPAN DE CARPIO',
            46: 'COSAUTLÁN DE CARVAJAL',
            47: 'COSCOMATEPEC',
            48: 'COSOLEACAQUE',
            49: 'COTAXTLA',
            50: 'COXQUIHUI',
            51: 'COYUTLA',
            52: 'CUICHAPA',
            53: 'CUITLÁHUAC',
            54: 'CHACALTIANGUIS',
            55: 'CHALMA',
            56: 'CHICONAMEL',
            57: 'CHICONQUIACO',
            58: 'CHICONTEPEC',
            59: 'CHINAMECA',
            60: 'CHINAMPA DE GOROSTIZA',
            61: 'LAS CHOAPAS',
            62: 'CHOCAMÁN',
            63: 'CHONTLA',
            64: 'CHUMATLÁN',
            65: 'EMILIANO ZAPATA',
            66: 'ESPINAL',
            67: 'FILOMENO MATA',
            68: 'FORTÍN',
            69: 'GUTIÉRREZ ZAMORA',
            70: 'HIDALGOTITLÁN',
            71: 'HUATUSCO',
            72: 'HUAYACOCOTLA',
            73: 'HUEYAPAN DE OCAMPO',
            74: 'HUILOAPAN DE CUAUHTÉMOC',
            75: 'IGNACIO DE LA LLAVE',
            76: 'ILAMATLÁN',
            77: 'ISLA',
            78: 'IXCATEPEC',
            79: 'IXHUACÁN DE LOS REYES',
            80: 'IXHUATLÁN DEL CAFÉ',
            81: 'IXHUATLANCILLO',
            82: 'IXHUATLÁN DEL SURESTE',
            83: 'IXHUATLÁN DE MADERO',
            84: 'IXMATLAHUACAN',
            85: 'IXTACZOQUITLÁN',
            86: 'JALACINGO',
            87: 'XALAPA',
            88: 'JALCOMULCO',
            89: 'JÁLTIPAN',
            90: 'JAMAPA',
            91: 'JESÚS CARRANZA',
            92: 'XICO',
            93: 'JILOTEPEC',
            94: 'JUAN RODRÍGUEZ CLARA',
            95: 'JUCHIQUE DE FERRER',
            96: 'LANDERO Y COSS',
            97: 'LERDO DE TEJADA',
            98: 'MAGDALENA',
            99: 'MALTRATA',
            1: 'MANLIO FABIO ALTAMIRANO',
            101: 'MARIANO ESCOBEDO',
            102: 'MARTÍNEZ DE LA TORRE',
            103: 'MECATLÁN',
            104: 'MECAYAPAN',
            105: 'MEDELLÍN DE BRAVO',
            106: 'MIAHUATLÁN',
            107: 'LAS MINAS',
            108: 'MINATITLÁN',
            109: 'MISANTLA',
            110: 'MIXTLA DE ALTAMIRANO',
            111: 'MOLOACÁN',
            112: 'NAOLINCO',
            113: 'NARANJAL',
            114: 'NAUTLA',
            115: 'NOGALES',
            116: 'OLUTA',
            117: 'OMEALCA',
            118: 'ORIZABA',
            119: 'OTATITLÁN',
            120: 'OTEAPAN',
            121: 'OZULUAMA DE MASCAREÑAS',
            122: 'PAJAPAN',
            123: 'PÁNUCO',
            124: 'PAPANTLA',
            125: 'PASO DEL MACHO',
            126: 'PASO DE OVEJAS',
            127: 'LA PERLA',
            128: 'PEROTE',
            129: 'PLATÓN SÁNCHEZ',
            130: 'PLAYA VICENTE',
            131: 'POZA RICA DE HIDALGO',
            132: 'LAS VIGAS DE RAMÍREZ',
            133: 'PUEBLO VIEJO',
            134: 'PUENTE NACIONAL',
            135: 'RAFAEL DELGADO',
            136: 'RAFAEL LUCIO',
            137: 'LOS REYES',
            138: 'RÍO BLANCO',
            139: 'SALTABARRANCA',
            140: 'SAN ANDRÉS TENEJAPAN',
            141: 'SAN ANDRÉS TUXTLA',
            142: 'SAN JUAN EVANGELISTA',
            143: 'SANTIAGO TUXTLA',
            144: 'SAYULA DE ALEMÁN',
            145: 'SOCONUSCO',
            146: 'SOCHIAPA',
            147: 'SOLEDAD ATZOMPA',
            148: 'SOLEDAD DE DOBLADO',
            149: 'SOTEAPAN',
            150: 'TAMALÍN',
            151: 'TAMIAHUA',
            152: 'TAMPICO ALTO',
            153: 'TANCOCO',
            154: 'TANTIMA',
            155: 'TANTOYUCA',
            156: 'TATATILA',
            157: 'CASTILLO DE TEAYO',
            158: 'TECOLUTLA',
            159: 'TEHUIPANGO',
            160: 'ÁLAMO TEMAPACHE',
            161: 'TEMPOAL',
            162: 'TENAMPA',
            163: 'TENOCHTITLÁN',
            164: 'TEOCELO',
            165: 'TEPATLAXCO',
            166: 'TEPETLÁN',
            167: 'TEPETZINTLA',
            168: 'TEQUILA',
            169: 'JOSÉ AZUETA',
            170: 'TEXCATEPEC',
            171: 'TEXHUACÁN',
            172: 'TEXISTEPEC',
            173: 'TEZONAPA',
            174: 'TIERRA BLANCA',
            175: 'TIHUATLÁN',
            176: 'TLACOJALPAN',
            177: 'TLACOLULAN',
            178: 'TLACOTALPAN',
            179: 'TLACOTEPEC DE MEJÍA',
            180: 'TLACHICHILCO',
            181: 'TLALIXCOYAN',
            182: 'TLALNELHUAYOCAN',
            183: 'TLAPACOYAN',
            184: 'TLAQUILPA',
            185: 'TLILAPAN',
            186: 'TOMATLÁN',
            187: 'TONAYÁN',
            188: 'TOTUTLA',
            189: 'TUXPAN',
            190: 'TUXTILLA',
            191: 'URSULO GALVÁN',
            192: 'VEGA DE ALATORRE',
            193: 'VERACRUZ',
            194: 'VILLA ALDAMA',
            195: 'XOXOCOTLA',
            196: 'YANGA',
            197: 'YECUATLA',
            198: 'ZACUALPAN',
            199: 'ZARAGOZA',
            2: 'ZENTLA',
            201: 'ZONGOLICA',
            202: 'ZONTECOMATLÁN DE LÓPEZ Y FUENTES',
            203: 'ZOZOCOLCO DE HIDALGO',
            204: 'AGUA DULCE',
            205: 'EL HIGO',
            206: 'NANCHITAL DE LÁZARO CÁRDENAS DEL RÍO',
            207: 'TRES VALLES',
            208: 'CARLOS A. CARRILLO',
            209: 'TATAHUICAPAN DE JUÁREZ',
            210: 'UXPANAPA',
            211: 'SAN RAFAEL',
            212: 'SANTIAGO SOCHIAPAN',
            999: 'NO ESPECIFICADO',
        }, 31: {
            1: 'ABALÁ',
            2: 'ACANCEH',
            3: 'AKIL',
            4: 'BACA',
            5: 'BOKOBÁ',
            6: 'BUCTZOTZ',
            7: 'CACALCHÉN',
            8: 'CALOTMUL',
            9: 'CANSAHCAB',
            10: 'CANTAMAYEC',
            11: 'CELESTÚN',
            12: 'CENOTILLO',
            13: 'CONKAL',
            14: 'CUNCUNUL',
            15: 'CUZAMÁ',
            16: 'CHACSINKÍN',
            17: 'CHANKOM',
            18: 'CHAPAB',
            19: 'CHEMAX',
            20: 'CHICXULUB PUEBLO',
            21: 'CHICHIMILÁ',
            22: 'CHIKINDZONOT',
            23: 'CHOCHOLÁ',
            24: 'CHUMAYEL',
            25: 'DZÁN',
            26: 'DZEMUL',
            27: 'DZIDZANTÚN',
            28: 'DZILAM DE BRAVO',
            29: 'DZILAM GONZÁLEZ',
            30: 'DZITÁS',
            31: 'DZONCAUICH',
            32: 'ESPITA',
            33: 'HALACHÓ',
            34: 'HOCABÁ',
            35: 'HOCTÚN',
            36: 'HOMÚN',
            37: 'HUHÍ',
            38: 'HUNUCMÁ',
            39: 'IXIL',
            40: 'IZAMAL',
            41: 'KANASÍN',
            42: 'KANTUNIL',
            43: 'KAUA',
            44: 'KINCHIL',
            45: 'KOPOMÁ',
            46: 'MAMA',
            47: 'MANÍ',
            48: 'MAXCANÚ',
            49: 'MAYAPÁN',
            50: 'MÉRIDA',
            51: 'MOCOCHÁ',
            52: 'MOTUL',
            53: 'MUNA',
            54: 'MUXUPIP',
            55: 'OPICHÉN',
            56: 'OXKUTZCAB',
            57: 'PANABÁ',
            58: 'PETO',
            59: 'PROGRESO',
            60: 'QUINTANA ROO',
            61: 'RÍO LAGARTOS',
            62: 'SACALUM',
            63: 'SAMAHIL',
            64: 'SANAHCAT',
            65: 'SAN FELIPE',
            66: 'SANTA ELENA',
            67: 'SEYÉ',
            68: 'SINANCHÉ',
            69: 'SOTUTA',
            70: 'SUCILÁ',
            71: 'SUDZAL',
            72: 'SUMA',
            73: 'TAHDZIÚ',
            74: 'TAHMEK',
            75: 'TEABO',
            76: 'TECOH',
            77: 'TEKAL DE VENEGAS',
            78: 'TEKANTÓ',
            79: 'TEKAX',
            80: 'TEKIT',
            81: 'TEKOM',
            82: 'TELCHAC PUEBLO',
            83: 'TELCHAC PUERTO',
            84: 'TEMAX',
            85: 'TEMOZÓN',
            86: 'TEPAKÁN',
            87: 'TETIZ',
            88: 'TEYA',
            89: 'TICUL',
            90: 'TIMUCUY',
            91: 'TINUM',
            92: 'TIXCACALCUPUL',
            93: 'TIXKOKOB',
            94: 'TIXMEHUAC',
            95: 'TIXPÉHUAL',
            96: 'TIZIMÍN',
            97: 'TUNKÁS',
            98: 'TZUCACAB',
            99: 'UAYMA',
            1: 'UCÚ',
            101: 'UMÁN',
            102: 'VALLADOLID',
            103: 'XOCCHEL',
            104: 'YAXCABÁ',
            105: 'YAXKUKUL',
            106: 'YOBAÍN',
            999: 'NO ESPECIFICADO',
        }, 32: {
            1: 'APOZOL',
            2: 'APULCO',
            3: 'ATOLINGA',
            4: 'BENITO JUÁREZ',
            5: 'CALERA',
            6: 'CAÑITAS DE FELIPE PESCADOR',
            7: 'CONCEPCIÓN DEL ORO',
            8: 'CUAUHTÉMOC',
            9: 'CHALCHIHUITES',
            10: 'FRESNILLO',
            11: 'TRINIDAD GARCÍA DE LA CADENA',
            12: 'GENARO CODINA',
            13: 'GENERAL ENRIQUE ESTRADA',
            14: 'GENERAL FRANCISCO R. MURGUÍA',
            15: 'EL PLATEADO DE JOAQUÍN AMARO',
            16: 'GENERAL PÁNFILO NATERA',
            17: 'GUADALUPE',
            18: 'HUANUSCO',
            19: 'JALPA',
            20: 'JEREZ',
            21: 'JIMÉNEZ DEL TEUL',
            22: 'JUAN ALDAMA',
            23: 'JUCHIPILA',
            24: 'LORETO',
            25: 'LUIS MOYA',
            26: 'MAZAPIL',
            27: 'MELCHOR OCAMPO',
            28: 'MEZQUITAL DEL ORO',
            29: 'MIGUEL AUZA',
            30: 'MOMAX',
            31: 'MONTE ESCOBEDO',
            32: 'MORELOS',
            33: 'MOYAHUA DE ESTRADA',
            34: 'NOCHISTLÁN DE MEJÍA',
            35: 'NORIA DE ÁNGELES',
            36: 'OJOCALIENTE',
            37: 'PÁNUCO',
            38: 'PINOS',
            39: 'RÍO GRANDE',
            40: 'SAIN ALTO',
            41: 'EL SALVADOR',
            42: 'SOMBRERETE',
            43: 'SUSTICACÁN',
            44: 'TABASCO',
            45: 'TEPECHITLÁN',
            46: 'TEPETONGO',
            47: 'TEÚL DE GONZÁLEZ ORTEGA',
            48: 'TLALTENANGO DE SÁNCHEZ ROMÁN',
            49: 'VALPARAÍSO',
            50: 'VETAGRANDE',
            51: 'VILLA DE COS',
            52: 'VILLA GARCÍA',
            53: 'VILLA GONZÁLEZ ORTEGA',
            54: 'VILLA HIDALGO',
            55: 'VILLANUEVA',
            56: 'ZACATECAS',
            57: 'TRANCOSO',
            58: 'SANTA MARÍA DE LA PAZ',
            999: 'NO ESPECIFICADO',
        }, 36: {
            999: 'NO ESPECIFICADO',
        }, 97: {
            997: 'NO APLICA',
        }, 98: {
            998: 'SE IGNORA',
        }, 99: {
            999: 'NO ESPECIFICADO'}
    }

    @classmethod
    def nombre(cls, estado_id, municipio_id):

        if not isinstance(estado_id, int) or not isinstance(municipio_id, int):
            return 'No encontrado'

        return cls.nombres[estado_id][municipio_id]
